"use client";

import * as React from "react";
import { Output, Field, Notice } from "@/components/tools/shared";
import { cn } from "@/lib/utils";
import { brand } from "@/lib/brand";
import { GITIGNORE_TEMPLATES, GITIGNORE_NAMES } from "@/lib/data/gitignore";

/* --------------------------- .gitignore Generator -------------------------- */
export function GitignoreGenerator() {
  const [selected, setSelected] = React.useState<string[]>(["Node", "macOS"]);

  const toggle = (name: string) =>
    setSelected((s) => (s.includes(name) ? s.filter((n) => n !== name) : [...s, name]));

  // Merge selected templates, de-duplicating patterns across all of them.
  const { output, saved } = React.useMemo(() => {
    const seen = new Set<string>();
    const blocks: string[] = [];
    let total = 0;
    let kept = 0;
    for (const name of selected) {
      const lines = GITIGNORE_TEMPLATES[name] ?? [];
      const unique: string[] = [];
      for (const line of lines) {
        total++;
        const key = line.trim();
        if (key.startsWith("!") || !seen.has(key)) {
          seen.add(key);
          unique.push(line);
          kept++;
        }
      }
      if (unique.length) blocks.push(`# ---- ${name} ----\n${unique.join("\n")}`);
    }
    const header = `# Generated by ${brand.name} .gitignore Generator\n`;
    return {
      output: blocks.length ? header + "\n" + blocks.join("\n\n") + "\n" : "",
      saved: total - kept,
    };
  }, [selected]);

  return (
    <div className="space-y-5">
      <Field
        label="Pick languages, frameworks & tools"
        hint="Selections are merged into one file and duplicate patterns are removed automatically."
      >
        <div className="flex flex-wrap gap-2">
          {GITIGNORE_NAMES.map((name) => {
            const on = selected.includes(name);
            return (
              <button
                key={name}
                type="button"
                onClick={() => toggle(name)}
                aria-pressed={on}
                className={cn(
                  "rounded-full border px-3.5 py-1.5 text-sm font-medium transition",
                  on
                    ? "border-brand bg-brand/10 text-brand"
                    : "border-border bg-surface-2 text-muted hover:border-brand/40 hover:text-foreground",
                )}
              >
                {name}
              </button>
            );
          })}
        </div>
      </Field>

      {selected.length === 0 ? (
        <Notice tone="info">Select at least one template to generate a .gitignore file.</Notice>
      ) : (
        <Field label="Generated .gitignore">
          <Output value={output} rows={16} filename=".gitignore" mime="text/plain" />
          {saved > 0 && (
            <p className="mt-1 text-xs text-muted">
              Merged {selected.length} templates and removed {saved} duplicate{" "}
              {saved === 1 ? "pattern" : "patterns"}.
            </p>
          )}
        </Field>
      )}
    </div>
  );
}
