"use client";

import { makeReg } from "./_util";
import {
  AbsorptionRateCalculator,
  AcTonnageCalculator,
  AirChangesCalculator,
  AquariumCalculator,
  BtuCalculator,
  BudgetCalculator,
  BusinessValuationCalculator,
  CarTradeEquityCalculator,
  CatAgeCalculator,
  CfmCalculator,
  ClosingCostCalculator,
  CoffeeRatioCalculator,
  CompostCalculator,
  DeckCalculator,
  DownPaymentCalculator,
  ElectricityCostCalculator,
  EmployeeCostCalculator,
  EvChargingCostCalculator,
  FuelMixCalculator,
  HexagonQuiltCalculator,
  HullSpeedCalculator,
  KerfCalculator,
  KwKvaCalculator,
  LoanComparisonCalculator,
  LumberCalculator,
  MarketplaceFeeCalculator,
  MiterAngleCalculator,
  MolarityCalculator,
  OhmsLawCalculator,
  PlantSpacingCalculator,
  PrintCostCalculator,
  RefinanceCalculator,
  RentalPropertyCalculator,
  RetirementCalculator,
  SellerNetCalculator,
  SprayFoamCalculator,
  TithingCalculator,
  VehicleDepreciationCalculator,
  VoltageDropCalculator,
  WireSizeCalculator,
} from "@/components/tools/impl/home-trade-calcs";

export default makeReg({
  "btu-calculator": BtuCalculator,
  "ac-tonnage-calculator": AcTonnageCalculator,
  "cfm-calculator": CfmCalculator,
  "air-changes-calculator": AirChangesCalculator,
  "lumber-calculator": LumberCalculator,
  "deck-calculator": DeckCalculator,
  "spray-foam-calculator": SprayFoamCalculator,
  "miter-angle-calculator": MiterAngleCalculator,
  "kerf-calculator": KerfCalculator,
  "ohms-law-calculator": OhmsLawCalculator,
  "voltage-drop-calculator": VoltageDropCalculator,
  "wire-size-calculator": WireSizeCalculator,
  "kw-to-kva-calculator": KwKvaCalculator,
  "electricity-cost-calculator": ElectricityCostCalculator,
  "ev-charging-cost-calculator": EvChargingCostCalculator,
  "closing-cost-calculator": ClosingCostCalculator,
  "down-payment-calculator": DownPaymentCalculator,
  "refinance-calculator": RefinanceCalculator,
  "rental-property-calculator": RentalPropertyCalculator,
  "seller-net-calculator": SellerNetCalculator,
  "loan-comparison-calculator": LoanComparisonCalculator,
  "budget-calculator": BudgetCalculator,
  "vehicle-depreciation-calculator": VehicleDepreciationCalculator,
  "marketplace-fee-calculator": MarketplaceFeeCalculator,
  "tithing-calculator": TithingCalculator,
  "retirement-calculator": RetirementCalculator,
  "employee-cost-calculator": EmployeeCostCalculator,
  "absorption-rate-calculator": AbsorptionRateCalculator,
  "car-trade-equity-calculator": CarTradeEquityCalculator,
  "business-valuation-calculator": BusinessValuationCalculator,
  "aquarium-calculator": AquariumCalculator,
  "coffee-ratio-calculator": CoffeeRatioCalculator,
  "3d-print-cost-calculator": PrintCostCalculator,
  "cat-age-calculator": CatAgeCalculator,
  "plant-spacing-calculator": PlantSpacingCalculator,
  "compost-calculator": CompostCalculator,
  "hull-speed-calculator": HullSpeedCalculator,
  "fuel-mix-calculator": FuelMixCalculator,
  "molarity-calculator": MolarityCalculator,
  "hexagon-quilt-calculator": HexagonQuiltCalculator,
});
