"use client";

import { makeReg } from "./_util";
import {
  MetaTagGenerator, OpenGraphGenerator, TwitterCardGenerator, KeywordDensity, RobotsTxtGenerator,
  SitemapGenerator, SchemaGenerator, UtmBuilder, SerpPreview, MetaDescriptionLengthChecker,
  MetaTitleLengthChecker, CanonicalTag, RobotsMetaTag, HreflangTag,
  HtmlTagStripper, EmailExtractor, CodeTextRatio, KeywordCombiner, ReadabilityChecker, HtaccessGenerator,
  MetaTagsAnalyzer, RobotsValidator,
} from "@/components/tools/impl/seo";
import {
  RelatedKeywordsGenerator,
  KeywordDifficultyEstimator,
  SearchIntentClassifier,
  XmlSitemapValidator,
  HeadingStructureAnalyzer,
  SeoAuditChecklist,
  SeoContentScore,
  KeywordRankTracker,
  BacklinkProfileAnalyzer,
  DisavowFileGenerator,
  InternalLinkSuggester,
  OrphanPageFinder,
  SchemaMarkupValidator,
  HowToSchemaGenerator,
  LocalBusinessSchemaGenerator,
  NapConsistencyChecker,
  UrlPageSeoAnalyzer,
} from "@/components/tools/impl/seo-suite";
import { UrlTool } from "@/components/tools/impl/data";
import { WordCounter, CharacterCounter, SlugTool, DiffChecker } from "@/components/tools/impl/text";
import { FaviconGenerator } from "@/components/tools/impl/image";
import { DomainNameFinder } from "@/components/tools/impl/domain";
import { LlmsTxtGenerator, SecurityHeadersGenerator, AdsTxtGenerator } from "@/components/tools/impl/high-demand";
import { AiTool } from "@/components/tools/impl/ai";

export default makeReg({
  "meta-tag-generator": MetaTagGenerator,
  "keyword-density-checker": KeywordDensity,
  "robots-txt-generator": RobotsTxtGenerator,
  "xml-sitemap-generator": SitemapGenerator,
  "schema-markup-generator": () => <SchemaGenerator kind="auto" />,
  "open-graph-generator": OpenGraphGenerator,
  "twitter-card-generator": TwitterCardGenerator,
  "serp-snippet-preview": SerpPreview,
  "htaccess-generator": HtaccessGenerator,
  "url-encoder-decoder": UrlTool,
  "url-slug-generator": SlugTool,
  "word-counter": WordCounter,
  "character-counter": CharacterCounter,
  "code-to-text-ratio-checker": CodeTextRatio,
  "robots-meta-tag-generator": RobotsMetaTag,
  "canonical-tag-generator": CanonicalTag,
  "hreflang-tag-generator": HreflangTag,
  "keyword-combiner": KeywordCombiner,
  "utm-builder": UtmBuilder,
  "html-tag-stripper": HtmlTagStripper,
  "meta-description-length-checker": MetaDescriptionLengthChecker,
  "meta-title-length-checker": MetaTitleLengthChecker,
  "text-diff-checker": DiffChecker,
  "faq-schema-generator": () => <SchemaGenerator kind="faq" />,
  "breadcrumb-schema-generator": () => <SchemaGenerator kind="breadcrumb" />,
  "redirect-checker": HtaccessGenerator,
  "email-extractor": EmailExtractor,
  "readability-checker": ReadabilityChecker,
  "meta-tags-analyzer": MetaTagsAnalyzer,
  "robots-txt-validator": RobotsValidator,
  "favicon-generator": FaviconGenerator,
  "domain-name-finder": DomainNameFinder,
  "llms-txt-generator": LlmsTxtGenerator,
  "security-headers-generator": SecurityHeadersGenerator,
  "ads-txt-generator": AdsTxtGenerator,
  "url-page-seo-analyzer": UrlPageSeoAnalyzer,
  /* —— new comprehensive SEO suite —— */
  "related-keywords-generator": RelatedKeywordsGenerator,
  "keyword-difficulty-estimator": KeywordDifficultyEstimator,
  "search-intent-classifier": SearchIntentClassifier,
  "xml-sitemap-validator": XmlSitemapValidator,
  "heading-structure-analyzer": HeadingStructureAnalyzer,
  "seo-audit-checklist": SeoAuditChecklist,
  "seo-content-score": SeoContentScore,
  "keyword-rank-tracker": KeywordRankTracker,
  "backlink-profile-analyzer": BacklinkProfileAnalyzer,
  "disavow-file-generator": DisavowFileGenerator,
  "internal-link-suggester": InternalLinkSuggester,
  "orphan-page-finder": OrphanPageFinder,
  "schema-markup-validator": SchemaMarkupValidator,
  "howto-schema-generator": HowToSchemaGenerator,
  "local-business-schema-generator": LocalBusinessSchemaGenerator,
  "nap-consistency-checker": NapConsistencyChecker,
  "content-brief-generator": () => <AiTool slug="content-brief-generator" />,
  "ai-meta-tag-writer": () => <AiTool slug="ai-meta-tag-writer" />,
  "ai-seo-outline-generator": () => <AiTool slug="ai-seo-outline-generator" />,
  "ai-seo-page-audit": () => <AiTool slug="ai-seo-page-audit" />,
});
