#!/usr/bin/env node
/** Generates src/i18n/messages/locales/*.json from embedded translations. */
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src/i18n/messages/locales");
mkdirSync(outDir, { recursive: true });

const CAT_KEYS = [
  "ai-tools",
  "handwriting-ocr",
  "devops-tools",
  "health-tools",
  "text-tools",
  "developer-tools",
  "security-password-tools",
  "pdf-tools",
  "image-tools",
  "color-tools",
  "calculators",
  "unit-converters",
  "seo-web-tools",
  "social-media-tools",
  "converters-generators",
];

/** @type {Record<string, string[]>} */
const CATEGORY_NAMES = {
  en: ["AI-Powered Tools", "Handwriting OCR", "DevOps Tools", "Health & Fitness", "Text Tools", "Developer Tools", "Security & Password Tools", "PDF Tools", "Image Tools", "Color Tools", "Calculators", "Unit Converters", "SEO & Web Tools", "Social Media Tools", "Converters & Generators"],
  ur: ["AI ٹولز", "ہینڈرائٹنگ OCR", "DevOps ٹولز", "صحت و فٹنس", "ٹیکسٹ ٹولز", "ڈیولپر ٹولز", "سیکیورٹی و پاس ورڈ", "PDF ٹولز", "تصویر ٹولز", "رنگ ٹولز", "کیلکولیٹر", "یونٹ کنورٹر", "SEO و ویب ٹولز", "سوشل میڈیا ٹولز", "کنورٹر و جنریٹر"],
  ar: ["أدوات الذكاء الاصطناعي", "OCR للخط اليدوي", "أدوات DevOps", "الصحة واللياقة", "أدوات النص", "أدوات المطورين", "الأمان وكلمات المرور", "أدوات PDF", "أدوات الصور", "أدوات الألوان", "الآلات الحاسبة", "محولات الوحدات", "أدوات SEO والويب", "أدوات وسائل التواصل", "المحولات والمولدات"],
  fa: ["ابزارهای هوش مصنوعی", "OCR دست‌خط", "ابزارهای DevOps", "سلامت و تناسب", "ابزارهای متن", "ابزارهای توسعه‌دهنده", "امنیت و رمز عبور", "ابزارهای PDF", "ابزارهای تصویر", "ابزارهای رنگ", "ماشین‌حساب", "مبدل واحد", "ابزارهای SEO و وب", "ابزارهای شبکه‌های اجتماعی", "مبدل‌ها و مولدها"],
  ps: ["AI وسیلې", "لاسلي OCR", "DevOps وسیلې", "روغتیا", "متن وسیلې", "Developer وسیلې", "امنیت", "PDF وسیلې", "انځور وسیلې", "رنګ وسیلې", "حساب", "Unit Converter", "SEO وسیلې", "Social Media", "Converters"],
  hi: ["AI टूल्स", "हस्तलेख OCR", "DevOps टूल्स", "स्वास्थ्य और फिटनेस", "टेक्स्ट टूल्स", "डेवलपर टूल्स", "सुरक्षा और पासवर्ड", "PDF टूल्स", "इमेज टूल्स", "रंग टूल्स", "कैलकुलेटर", "यूनिट कनverter", "SEO और वेब टूल्स", "सोशल मीडिया टूल्स", "कनverter और जेनरेटर"],
  bn: ["AI টুলস", "হাতের লেখা OCR", "DevOps টুলস", "স্বাস্থ্য", "টেক্সট টুলস", "ডেভেলপার টুলস", "নিরাপত্তা", "PDF টুলস", "ইমেজ টুলস", "রঙ টুলস", "ক্যালকুলেটর", "ইউনিট কনভার্টার", "SEO টুলস", "সোশ্যাল মিডিয়া", "কনভার্টার"],
  pa: ["AI ਟੂਲ", "ਹੱਥਲਿਖਤ OCR", "DevOps ਟੂਲ", "ਸਿਹਤ", "ਟੈਕਸਟ ਟੂਲ", "Developer ਟੂਲ", "ਸੁਰੱਖਿਆ", "PDF ਟੂਲ", "ਚਿੱਤਰ ਟੂਲ", "ਰੰਗ ਟੂਲ", "ਕੈਲਕੁਲੇਟਰ", "ਯੂਨਿਟ ਕਨਵਰਟਰ", "SEO ਟੂਲ", "ਸੋਸ਼ਲ ਮੀਡੀਆ", "ਕਨਵਰਟਰ"],
  tr: ["Yapay Zeka Araçları", "El Yazısı OCR", "DevOps Araçları", "Sağlık ve Fitness", "Metin Araçları", "Geliştirici Araçları", "Güvenlik ve Şifre", "PDF Araçları", "Görsel Araçları", "Renk Araçları", "Hesap Makineleri", "Birim Dönüştürücüler", "SEO ve Web Araçları", "Sosyal Medya Araçları", "Dönüştürücüler ve Oluşturucular"],
  id: ["Alat AI", "OCR Tulisan Tangan", "Alat DevOps", "Kesehatan & Kebugaran", "Alat Teks", "Alat Developer", "Keamanan & Kata Sandi", "Alat PDF", "Alat Gambar", "Alat Warna", "Kalkulator", "Konverter Satuan", "Alat SEO & Web", "Alat Media Sosial", "Konverter & Generator"],
  ms: ["Alat AI", "OCR Tulisan Tangan", "Alat DevOps", "Kesihatan & Kecergasan", "Alat Teks", "Alat Pembangun", "Keselamatan & Kata Laluan", "Alat PDF", "Alat Imej", "Alat Warna", "Kalkulator", "Penukar Unit", "Alat SEO & Web", "Alat Media Sosial", "Penukar & Penjana"],
  es: ["Herramientas de IA", "OCR de escritura", "Herramientas DevOps", "Salud y fitness", "Herramientas de texto", "Herramientas para desarrolladores", "Seguridad y contraseñas", "Herramientas PDF", "Herramientas de imagen", "Herramientas de color", "Calculadoras", "Convertidores de unidades", "Herramientas SEO y web", "Redes sociales", "Convertidores y generadores"],
  pt: ["Ferramentas de IA", "OCR de escrita", "Ferramentas DevOps", "Saúde e fitness", "Ferramentas de texto", "Ferramentas para desenvolvedores", "Segurança e senhas", "Ferramentas PDF", "Ferramentas de imagem", "Ferramentas de cor", "Calculadoras", "Conversores de unidades", "Ferramentas SEO e web", "Redes sociais", "Conversores e geradores"],
  fr: ["Outils IA", "OCR manuscrit", "Outils DevOps", "Santé et fitness", "Outils texte", "Outils développeur", "Sécurité et mots de passe", "Outils PDF", "Outils image", "Outils couleur", "Calculatrices", "Convertisseurs d'unités", "Outils SEO et web", "Réseaux sociaux", "Convertisseurs et générateurs"],
  de: ["KI-Tools", "Handschrift-OCR", "DevOps-Tools", "Gesundheit & Fitness", "Text-Tools", "Entwickler-Tools", "Sicherheit & Passwörter", "PDF-Tools", "Bild-Tools", "Farb-Tools", "Rechner", "Einheitenumrechner", "SEO- & Web-Tools", "Social-Media-Tools", "Konverter & Generatoren"],
  it: ["Strumenti IA", "OCR scrittura", "Strumenti DevOps", "Salute e fitness", "Strumenti testo", "Strumenti per sviluppatori", "Sicurezza e password", "Strumenti PDF", "Strumenti immagine", "Strumenti colore", "Calcolatrici", "Convertitori di unità", "Strumenti SEO e web", "Social media", "Convertitori e generatori"],
  nl: ["AI-tools", "Handschrift-OCR", "DevOps-tools", "Gezondheid & fitness", "Teksttools", "Ontwikkelaarstools", "Beveiliging & wachtwoorden", "PDF-tools", "Afbeeldingstools", "Kleurtools", "Rekenmachines", "Eenhedenconverters", "SEO- & webtools", "Social media", "Converters & generators"],
  ru: ["ИИ-инструменты", "OCR рукописи", "DevOps-инструменты", "Здоровье и фитнес", "Текстовые инструменты", "Инструменты разработчика", "Безопасность и пароли", "PDF-инструменты", "Инструменты для изображений", "Цветовые инструменты", "Калькуляторы", "Конвертеры единиц", "SEO и веб-инструменты", "Соцсети", "Конвертеры и генераторы"],
  uk: ["Інструменти ШІ", "OCR рукопису", "DevOps-інструменти", "Здоров'я та фітнес", "Текстові інструменти", "Інструменти розробника", "Безпека та паролі", "PDF-інструменти", "Інструменти зображень", "Кольорові інструменти", "Калькулятори", "Конвертери одиниць", "SEO та веб-інструменти", "Соцмережі", "Конвертери та генератори"],
  pl: ["Narzędzia AI", "OCR pisma ręcznego", "Narzędzia DevOps", "Zdrowie i fitness", "Narzędzia tekstowe", "Narzędzia dla deweloperów", "Bezpieczeństwo i hasła", "Narzędzia PDF", "Narzędzia obrazów", "Narzędzia kolorów", "Kalkulatory", "Konwertery jednostek", "Narzędzia SEO i web", "Media społecznościowe", "Konwertery i generatory"],
  zh: ["AI 工具", "手写 OCR", "DevOps 工具", "健康与健身", "文本工具", "开发者工具", "安全与密码", "PDF 工具", "图片工具", "颜色工具", "计算器", "单位转换", "SEO 与网页工具", "社交媒体工具", "转换与生成器"],
  ja: ["AIツール", "手書きOCR", "DevOpsツール", "健康・フィットネス", "テキストツール", "開発者ツール", "セキュリティ・パスワード", "PDFツール", "画像ツール", "カラーツール", "計算機", "単位変換", "SEO・Webツール", "SNSツール", "変換・生成ツール"],
  ko: ["AI 도구", "손글씨 OCR", "DevOps 도구", "건강 및 피트니스", "텍스트 도구", "개발자 도구", "보안 및 비밀번호", "PDF 도구", "이미지 도구", "색상 도구", "계산기", "단위 변환", "SEO 및 웹 도구", "소셜 미디어 도구", "변환 및 생성기"],
  vi: ["Công cụ AI", "OCR chữ viết tay", "Công cụ DevOps", "Sức khỏe & thể dục", "Công cụ văn bản", "Công cụ lập trình", "Bảo mật & mật khẩu", "Công cụ PDF", "Công cụ ảnh", "Công cụ màu", "Máy tính", "Chuyển đổi đơn vị", "Công cụ SEO & web", "Mạng xã hội", "Chuyển đổi & tạo"],
  th: ["เครื่องมือ AI", "OCR ลายมือ", "เครื่องมือ DevOps", "สุขภาพและฟิตเนส", "เครื่องมือข้อความ", "เครื่องมือนักพัฒนา", "ความปลอดภัยและรหัสผ่าน", "เครื่องมือ PDF", "เครื่องมือรูปภาพ", "เครื่องมือสี", "เครื่องคิดเลข", "แปลงหน่วย", "เครื่องมือ SEO และเว็บ", "โซเชียลมีเดีย", "แปลงและสร้าง"],
  tl: ["Mga AI Tool", "Handwriting OCR", "DevOps Tools", "Kalusugan at Fitness", "Text Tools", "Developer Tools", "Seguridad at Password", "PDF Tools", "Image Tools", "Color Tools", "Calculators", "Unit Converters", "SEO at Web Tools", "Social Media Tools", "Converters at Generators"],
};

function cats(code) {
  const names = CATEGORY_NAMES[code] ?? CATEGORY_NAMES.en;
  return Object.fromEntries(CAT_KEYS.map((k, i) => [k, names[i]]));
}

/** @type {Record<string, object>} */
const LOCALES = {
  en: {
    nav: { categories: "Categories", allTools: "All Tools", pricing: "Pricing", search: "Search", menu: "Menu", toolsCount: "{n} tools" },
    auth: { signIn: "Sign in", signOut: "Sign out", managePro: "Manage Pro", upgradePro: "Upgrade to Pro" },
    home: { explore: "Explore", pickCategory: "Pick a category", pickCategorySub: "{n}+ tools, organized for you.", seeAll: "See all", trending: "Trending", trendingTitle: "Most popular right now", valuePrivate: "Private", valuePrivateDesc: "Runs in your browser", valueInstant: "Instant", valueInstantDesc: "No waiting around", valueOnline: "Online", valueOnlineDesc: "Works everywhere", ctaTitle: "Start using tools now", browseAll: "Browse all tools", searchAll: "Search all tools", heroEverything: "everything", heroYouDo: "you do.", searchPlaceholder: "Search {n}+ tools…", go: "Go", allToolsArrow: "All tools →", toolsInCategory: "{n} tools" },
    footer: { allTools: "All Tools", pricing: "Pricing", about: "About", privacy: "Privacy", copyright: "© {year} {name}" },
    notFound: { title: "404", message: "We couldn't find that page or tool.", goHome: "Go home", browseTools: "Browse tools" },
    copy: { tagline: "{n}+ Online Tools", taglineWithTier: "{n}+ tools · Free tier + Pro", siteDescription: "{total}+ online tools across {cats} categories. {client}+ browser tools are free with no signup. AI & OCR tools include {aiLimit} free runs per day — Pro adds unlimited AI and removes ads.", heroBadge: "{n}+ tools · Free tier + Pro", heroTitleLead: "Online tools for", heroSubtitle: "{client}+ browser tools free & unlimited. AI & OCR: {aiLimit} runs/day on Free — Pro for unlimited & no ads.", footerNote: "{client}+ browser tools free · Pro for unlimited AI", homeValueFreeTitle: "Free tier", homeValueFreeDesc: "{client}+ browser tools · {aiLimit} AI runs/day", homeCtaSubtitle: "{client}+ tools work without signup. AI daily limits on Free — upgrade to Pro anytime." },
  },
};

// Append translated UI packs (same keys as en)
Object.assign(LOCALES, {
  ur: { nav: { categories: "زمرے", allTools: "تمام ٹولز", pricing: "قیمتیں", search: "تلاش", menu: "مینو", toolsCount: "{n} ٹولز" }, auth: { signIn: "سائن ان", signOut: "سائن آؤٹ", managePro: "Pro منظم کریں", upgradePro: "Pro میں اپ گریڈ" }, home: { explore: "دریافت کریں", pickCategory: "زمرہ منتخب کریں", pickCategorySub: "{n}+ ٹولز، آپ کے لیے ترتیب شدہ۔", seeAll: "سب دیکھیں", trending: "مقبول", trendingTitle: "اب سب سے زیادہ مقبول", valuePrivate: "نجی", valuePrivateDesc: "آپ کے براؤزر میں چلتا ہے", valueInstant: "فوری", valueInstantDesc: "انتظار نہیں", valueOnline: "آن لائن", valueOnlineDesc: "ہر جگہ کام کرتا ہے", ctaTitle: "ابھی ٹولز استعمال کریں", browseAll: "تمام ٹولز دیکھیں", searchAll: "تمام ٹولز تلاش کریں", heroEverything: "ہر کام", heroYouDo: "کے لیے۔", searchPlaceholder: "{n}+ ٹولز تلاش کریں…", go: "جائیں", allToolsArrow: "تمام ٹولز ←", toolsInCategory: "{n} ٹولز" }, footer: { allTools: "تمام ٹولز", pricing: "قیمتیں", about: "ہمارے بارے میں", privacy: "رازداری", copyright: "© {year} {name}" }, notFound: { title: "404", message: "یہ صفحہ یا ٹول نہیں ملا۔", goHome: "ہوم پر جائیں", browseTools: "ٹولز دیکھیں" }, copy: { tagline: "{n}+ آن لائن ٹولز", taglineWithTier: "{n}+ ٹولز · مفت + Pro", siteDescription: "{cats} زمروں میں {total}+ آن لائن ٹولز۔ {client}+ براؤزر ٹولز بغیر سائن اپ مفت۔ AI و OCR پر روز {aiLimit} مفت رن — Pro سے لامحدود AI اور بغیر اشتہارات۔", heroBadge: "{n}+ ٹولز · مفت + Pro", heroTitleLead: "آن لائن ٹولز", heroSubtitle: "{client}+ براؤزر ٹولز مفت و لامحدود۔ AI و OCR: مفت پر روز {aiLimit} رن — Pro سے لامحدود و بغیر اشتہارات۔", footerNote: "{client}+ براؤزر ٹولز مفت · Pro سے لامحدود AI", homeValueFreeTitle: "مفت پلان", homeValueFreeDesc: "{client}+ براؤزر ٹولز · روز {aiLimit} AI رن", homeCtaSubtitle: "{client}+ ٹولز بغیر سائن اپ۔ مفت پر AI کی حد — Pro کسی وقت اپ گریڈ کریں۔" } },
  ar: { nav: { categories: "الفئات", allTools: "جميع الأدوات", pricing: "الأسعار", search: "بحث", menu: "القائمة", toolsCount: "{n} أداة" }, auth: { signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", managePro: "إدارة Pro", upgradePro: "ترقية إلى Pro" }, home: { explore: "استكشف", pickCategory: "اختر فئة", pickCategorySub: "{n}+ أداة، منظمة لك.", seeAll: "عرض الكل", trending: "رائج", trendingTitle: "الأكثر شعبية الآن", valuePrivate: "خاص", valuePrivateDesc: "يعمل في متصفحك", valueInstant: "فوري", valueInstantDesc: "بدون انتظار", valueOnline: "عبر الإنترنت", valueOnlineDesc: "يعمل في كل مكان", ctaTitle: "ابدأ استخدام الأدوات الآن", browseAll: "تصفح جميع الأدوات", searchAll: "ابحث في جميع الأدوات", heroEverything: "كل شيء", heroYouDo: "تفعله.", searchPlaceholder: "ابحث في {n}+ أداة…", go: "اذهب", allToolsArrow: "جميع الأدوات ←", toolsInCategory: "{n} أداة" }, footer: { allTools: "جميع الأدوات", pricing: "الأسعار", about: "من نحن", privacy: "الخصوصية", copyright: "© {year} {name}" }, notFound: { title: "404", message: "لم نعثر على هذه الصفحة أو الأداة.", goHome: "الصفحة الرئيسية", browseTools: "تصفح الأدوات" }, copy: { tagline: "{n}+ أداة عبر الإنترنت", taglineWithTier: "{n}+ أداة · مجاني + Pro", siteDescription: "{total}+ أداة عبر {cats} فئة. {client}+ أداة متصفح مجانية بدون تسجيل. AI و OCR: {aiLimit} تشغيل مجاني يومياً — Pro للامحدود وبدون إعلانات.", heroBadge: "{n}+ أداة · مجاني + Pro", heroTitleLead: "أدوات عبر الإنترنت لـ", heroSubtitle: "{client}+ أداة متصفح مجانية. AI و OCR: {aiLimit} تشغيل/يوم مجاناً — Pro للامحدود.", footerNote: "{client}+ أداة متصفح مجانية · Pro للامحدود", homeValueFreeTitle: "الخطة المجانية", homeValueFreeDesc: "{client}+ أداة · {aiLimit} تشغيل AI/يوم", homeCtaSubtitle: "{client}+ أداة بدون تسجيل. حدود AI على المجاني — ترقية إلى Pro في أي وقت." } },
  es: { nav: { categories: "Categorías", allTools: "Todas las herramientas", pricing: "Precios", search: "Buscar", menu: "Menú", toolsCount: "{n} herramientas" }, auth: { signIn: "Iniciar sesión", signOut: "Cerrar sesión", managePro: "Gestionar Pro", upgradePro: "Mejorar a Pro" }, home: { explore: "Explorar", pickCategory: "Elige una categoría", pickCategorySub: "{n}+ herramientas, organizadas para ti.", seeAll: "Ver todo", trending: "Tendencias", trendingTitle: "Lo más popular ahora", valuePrivate: "Privado", valuePrivateDesc: "Funciona en tu navegador", valueInstant: "Instantáneo", valueInstantDesc: "Sin esperas", valueOnline: "En línea", valueOnlineDesc: "Funciona en todas partes", ctaTitle: "Empieza a usar herramientas", browseAll: "Ver todas las herramientas", searchAll: "Buscar herramientas", heroEverything: "todo", heroYouDo: "lo que haces.", searchPlaceholder: "Buscar {n}+ herramientas…", go: "Ir", allToolsArrow: "Todas →", toolsInCategory: "{n} herramientas" }, footer: { allTools: "Todas las herramientas", pricing: "Precios", about: "Acerca de", privacy: "Privacidad", copyright: "© {year} {name}" }, notFound: { title: "404", message: "No encontramos esa página o herramienta.", goHome: "Inicio", browseTools: "Ver herramientas" }, copy: { tagline: "{n}+ herramientas en línea", taglineWithTier: "{n}+ herramientas · Gratis + Pro", siteDescription: "{total}+ herramientas en {cats} categorías. {client}+ herramientas de navegador gratis sin registro. AI y OCR: {aiLimit} usos gratis/día — Pro ilimitado sin anuncios.", heroBadge: "{n}+ herramientas · Gratis + Pro", heroTitleLead: "Herramientas en línea para", heroSubtitle: "{client}+ herramientas gratis. AI y OCR: {aiLimit} usos/día en Gratis — Pro ilimitado.", footerNote: "{client}+ herramientas gratis · Pro ilimitado", homeValueFreeTitle: "Plan gratis", homeValueFreeDesc: "{client}+ herramientas · {aiLimit} usos AI/día", homeCtaSubtitle: "{client}+ herramientas sin registro. Límites AI en Gratis — mejora a Pro cuando quieras." } },
  fr: { nav: { categories: "Catégories", allTools: "Tous les outils", pricing: "Tarifs", search: "Rechercher", menu: "Menu", toolsCount: "{n} outils" }, auth: { signIn: "Connexion", signOut: "Déconnexion", managePro: "Gérer Pro", upgradePro: "Passer à Pro" }, home: { explore: "Explorer", pickCategory: "Choisir une catégorie", pickCategorySub: "{n}+ outils, organisés pour vous.", seeAll: "Tout voir", trending: "Tendances", trendingTitle: "Les plus populaires", valuePrivate: "Privé", valuePrivateDesc: "Dans votre navigateur", valueInstant: "Instantané", valueInstantDesc: "Sans attente", valueOnline: "En ligne", valueOnlineDesc: "Partout", ctaTitle: "Utilisez les outils maintenant", browseAll: "Parcourir tous les outils", searchAll: "Rechercher", heroEverything: "tout", heroYouDo: "ce que vous faites.", searchPlaceholder: "Rechercher {n}+ outils…", go: "Go", allToolsArrow: "Tous →", toolsInCategory: "{n} outils" }, footer: { allTools: "Tous les outils", pricing: "Tarifs", about: "À propos", privacy: "Confidentialité", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Page ou outil introuvable.", goHome: "Accueil", browseTools: "Parcourir" }, copy: { tagline: "{n}+ outils en ligne", taglineWithTier: "{n}+ outils · Gratuit + Pro", siteDescription: "{total}+ outils dans {cats} catégories. {client}+ outils navigateur gratuits. AI et OCR : {aiLimit} exécutions/jour — Pro illimité sans pub.", heroBadge: "{n}+ outils · Gratuit + Pro", heroTitleLead: "Outils en ligne pour", heroSubtitle: "{client}+ outils gratuits. AI et OCR : {aiLimit}/jour — Pro illimité.", footerNote: "{client}+ outils gratuits · Pro illimité", homeValueFreeTitle: "Offre gratuite", homeValueFreeDesc: "{client}+ outils · {aiLimit} AI/jour", homeCtaSubtitle: "{client}+ outils sans inscription. Limites AI sur Gratuit — passez à Pro." } },
  de: { nav: { categories: "Kategorien", allTools: "Alle Tools", pricing: "Preise", search: "Suchen", menu: "Menü", toolsCount: "{n} Tools" }, auth: { signIn: "Anmelden", signOut: "Abmelden", managePro: "Pro verwalten", upgradePro: "Pro upgraden" }, home: { explore: "Entdecken", pickCategory: "Kategorie wählen", pickCategorySub: "{n}+ Tools, für Sie sortiert.", seeAll: "Alle anzeigen", trending: "Trending", trendingTitle: "Jetzt am beliebtesten", valuePrivate: "Privat", valuePrivateDesc: "Läuft im Browser", valueInstant: "Sofort", valueInstantDesc: "Kein Warten", valueOnline: "Online", valueOnlineDesc: "Überall", ctaTitle: "Jetzt Tools nutzen", browseAll: "Alle Tools", searchAll: "Tools suchen", heroEverything: "alles", heroYouDo: "was Sie tun.", searchPlaceholder: "{n}+ Tools suchen…", go: "Los", allToolsArrow: "Alle →", toolsInCategory: "{n} Tools" }, footer: { allTools: "Alle Tools", pricing: "Preise", about: "Über uns", privacy: "Datenschutz", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Seite oder Tool nicht gefunden.", goHome: "Startseite", browseTools: "Tools durchsuchen" }, copy: { tagline: "{n}+ Online-Tools", taglineWithTier: "{n}+ Tools · Kostenlos + Pro", siteDescription: "{total}+ Tools in {cats} Kategorien. {client}+ Browser-Tools kostenlos. AI & OCR: {aiLimit} Läufe/Tag — Pro unbegrenzt.", heroBadge: "{n}+ Tools · Kostenlos + Pro", heroTitleLead: "Online-Tools für", heroSubtitle: "{client}+ Tools kostenlos. AI & OCR: {aiLimit}/Tag — Pro unbegrenzt.", footerNote: "{client}+ Tools kostenlos · Pro unbegrenzt", homeValueFreeTitle: "Kostenlos", homeValueFreeDesc: "{client}+ Tools · {aiLimit} AI/Tag", homeCtaSubtitle: "{client}+ Tools ohne Anmeldung. AI-Limits im Free-Plan — Pro jederzeit." } },
  pt: { nav: { categories: "Categorias", allTools: "Todas as ferramentas", pricing: "Preços", search: "Buscar", menu: "Menu", toolsCount: "{n} ferramentas" }, auth: { signIn: "Entrar", signOut: "Sair", managePro: "Gerir Pro", upgradePro: "Upgrade para Pro" }, home: { explore: "Explorar", pickCategory: "Escolha uma categoria", pickCategorySub: "{n}+ ferramentas organizadas.", seeAll: "Ver tudo", trending: "Em alta", trendingTitle: "Mais populares agora", valuePrivate: "Privado", valuePrivateDesc: "No seu navegador", valueInstant: "Instantâneo", valueInstantDesc: "Sem espera", valueOnline: "Online", valueOnlineDesc: "Em todo lugar", ctaTitle: "Comece a usar agora", browseAll: "Ver todas", searchAll: "Buscar", heroEverything: "tudo", heroYouDo: "que você faz.", searchPlaceholder: "Buscar {n}+ ferramentas…", go: "Ir", allToolsArrow: "Todas →", toolsInCategory: "{n} ferramentas" }, footer: { allTools: "Todas", pricing: "Preços", about: "Sobre", privacy: "Privacidade", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Página ou ferramenta não encontrada.", goHome: "Início", browseTools: "Ver ferramentas" }, copy: { tagline: "{n}+ ferramentas online", taglineWithTier: "{n}+ · Grátis + Pro", siteDescription: "{total}+ ferramentas em {cats} categorias. {client}+ grátis no navegador. AI e OCR: {aiLimit} usos/dia — Pro ilimitado.", heroBadge: "{n}+ · Grátis + Pro", heroTitleLead: "Ferramentas online para", heroSubtitle: "{client}+ grátis. AI: {aiLimit}/dia — Pro ilimitado.", footerNote: "{client}+ grátis · Pro ilimitado", homeValueFreeTitle: "Plano grátis", homeValueFreeDesc: "{client}+ · {aiLimit} AI/dia", homeCtaSubtitle: "{client}+ sem cadastro. Limites no Grátis — upgrade Pro." } },
  hi: { nav: { categories: "श्रेणियाँ", allTools: "सभी टूल", pricing: "मूल्य", search: "खोजें", menu: "मेनू", toolsCount: "{n} टूल" }, auth: { signIn: "साइन इन", signOut: "साइन आउट", managePro: "Pro प्रबंधित", upgradePro: "Pro अपग्रेड" }, home: { explore: "खोजें", pickCategory: "श्रेणी चुनें", pickCategorySub: "{n}+ टूल, आपके लिए।", seeAll: "सभी देखें", trending: "ट्रेंडिंग", trendingTitle: "अभी लोकप्रिय", valuePrivate: "निजी", valuePrivateDesc: "ब्राउज़र में चलता है", valueInstant: "तुरंत", valueInstantDesc: "कोई इंतज़ार नहीं", valueOnline: "ऑनलाइन", valueOnlineDesc: "हर जगह", ctaTitle: "अभी टूल इस्तेमाल करें", browseAll: "सभी टूल", searchAll: "खोजें", heroEverything: "हर काम", heroYouDo: "के लिए।", searchPlaceholder: "{n}+ टूल खोजें…", go: "जाएँ", allToolsArrow: "सभी →", toolsInCategory: "{n} टूल" }, footer: { allTools: "सभी टूल", pricing: "मूल्य", about: "हमारे बारे में", privacy: "गोपनीयता", copyright: "© {year} {name}" }, notFound: { title: "404", message: "पृष्ठ या टूल नहीं मिला।", goHome: "होम", browseTools: "टूल देखें" }, copy: { tagline: "{n}+ ऑनलाइन टूल", taglineWithTier: "{n}+ · मुफ़्त + Pro", siteDescription: "{cats} श्रेणियों में {total}+ टूल। {client}+ ब्राउज़र टूल मुफ़्त। AI: {aiLimit} रन/दिन — Pro अनलिमिटेड।", heroBadge: "{n}+ · मुफ़्त + Pro", heroTitleLead: "ऑनलाइन टूल", heroSubtitle: "{client}+ मुफ़्त। AI: {aiLimit}/दिन — Pro अनलिमिटेड।", footerNote: "{client}+ मुफ़्त · Pro अनलिमिटेड", homeValueFreeTitle: "मुफ़्त प्लान", homeValueFreeDesc: "{client}+ · {aiLimit} AI/दिन", homeCtaSubtitle: "{client}+ बिना साइन अप। Pro कभी भी।" } },
  zh: { nav: { categories: "分类", allTools: "全部工具", pricing: "价格", search: "搜索", menu: "菜单", toolsCount: "{n} 个工具" }, auth: { signIn: "登录", signOut: "退出", managePro: "管理 Pro", upgradePro: "升级 Pro" }, home: { explore: "探索", pickCategory: "选择分类", pickCategorySub: "{n}+ 个工具，为您整理。", seeAll: "查看全部", trending: "热门", trendingTitle: "当前最受欢迎", valuePrivate: "私密", valuePrivateDesc: "在浏览器中运行", valueInstant: "即时", valueInstantDesc: "无需等待", valueOnline: "在线", valueOnlineDesc: "随处可用", ctaTitle: "立即使用工具", browseAll: "浏览全部", searchAll: "搜索工具", heroEverything: "一切", heroYouDo: "所需。", searchPlaceholder: "搜索 {n}+ 工具…", go: "前往", allToolsArrow: "全部 →", toolsInCategory: "{n} 个工具" }, footer: { allTools: "全部工具", pricing: "价格", about: "关于", privacy: "隐私", copyright: "© {year} {name}" }, notFound: { title: "404", message: "找不到该页面或工具。", goHome: "首页", browseTools: "浏览工具" }, copy: { tagline: "{n}+ 在线工具", taglineWithTier: "{n}+ · 免费 + Pro", siteDescription: "{cats} 个分类共 {total}+ 工具。{client}+ 浏览器工具免费。AI/OCR 每日 {aiLimit} 次免费 — Pro 无限。", heroBadge: "{n}+ · 免费 + Pro", heroTitleLead: "在线工具，助力", heroSubtitle: "{client}+ 免费工具。AI：每日 {aiLimit} 次 — Pro 无限。", footerNote: "{client}+ 免费 · Pro 无限", homeValueFreeTitle: "免费版", homeValueFreeDesc: "{client}+ · 每日 {aiLimit} 次 AI", homeCtaSubtitle: "{client}+ 无需注册。免费版有限制 — 随时升级 Pro。" } },
  ja: { nav: { categories: "カテゴリ", allTools: "すべてのツール", pricing: "料金", search: "検索", menu: "メニュー", toolsCount: "{n} ツール" }, auth: { signIn: "ログイン", signOut: "ログアウト", managePro: "Pro管理", upgradePro: "Proにアップグレード" }, home: { explore: "探索", pickCategory: "カテゴリを選ぶ", pickCategorySub: "{n}+ ツールを整理。", seeAll: "すべて", trending: "トレンド", trendingTitle: "人気のツール", valuePrivate: "プライベート", valuePrivateDesc: "ブラウザで実行", valueInstant: "即時", valueInstantDesc: "待ち時間なし", valueOnline: "オンライン", valueOnlineDesc: "どこでも", ctaTitle: "今すぐ使う", browseAll: "すべて見る", searchAll: "検索", heroEverything: "すべて", heroYouDo: "のために。", searchPlaceholder: "{n}+ ツールを検索…", go: "Go", allToolsArrow: "すべて →", toolsInCategory: "{n} ツール" }, footer: { allTools: "すべて", pricing: "料金", about: "概要", privacy: "プライバシー", copyright: "© {year} {name}" }, notFound: { title: "404", message: "ページまたはツールが見つかりません。", goHome: "ホーム", browseTools: "ツール一覧" }, copy: { tagline: "{n}+ オンラインツール", taglineWithTier: "{n}+ · 無料 + Pro", siteDescription: "{cats} カテゴリに {total}+ ツール。{client}+ ブラウザツール無料。AI/OCR 1日 {aiLimit} 回 — Pro 無制限。", heroBadge: "{n}+ · 無料 + Pro", heroTitleLead: "オンラインツール", heroSubtitle: "{client}+ 無料。AI: 1日 {aiLimit} 回 — Pro 無制限。", footerNote: "{client}+ 無料 · Pro 無制限", homeValueFreeTitle: "無料プラン", homeValueFreeDesc: "{client}+ · AI {aiLimit}/日", homeCtaSubtitle: "{client}+ 登録不要。Pro いつでも。" } },
  ko: { nav: { categories: "카테고리", allTools: "모든 도구", pricing: "요금", search: "검색", menu: "메뉴", toolsCount: "{n}개 도구" }, auth: { signIn: "로그인", signOut: "로그아웃", managePro: "Pro 관리", upgradePro: "Pro 업그레이드" }, home: { explore: "탐색", pickCategory: "카테고리 선택", pickCategorySub: "{n}+ 도구, 정리됨.", seeAll: "전체", trending: "인기", trendingTitle: "지금 인기", valuePrivate: "비공개", valuePrivateDesc: "브라우저에서 실행", valueInstant: "즉시", valueInstantDesc: "대기 없음", valueOnline: "온라인", valueOnlineDesc: "어디서나", ctaTitle: "지금 시작", browseAll: "모든 도구", searchAll: "검색", heroEverything: "모든", heroYouDo: "작업.", searchPlaceholder: "{n}+ 도구 검색…", go: "Go", allToolsArrow: "전체 →", toolsInCategory: "{n}개" }, footer: { allTools: "모든 도구", pricing: "요금", about: "소개", privacy: "개인정보", copyright: "© {year} {name}" }, notFound: { title: "404", message: "페이지 또는 도구를 찾을 수 없습니다.", goHome: "홈", browseTools: "도구 보기" }, copy: { tagline: "{n}+ 온라인 도구", taglineWithTier: "{n}+ · 무료 + Pro", siteDescription: "{cats}개 카테고리 {total}+ 도구. {client}+ 브라우저 도구 무료. AI {aiLimit}회/일 — Pro 무제한.", heroBadge: "{n}+ · 무료 + Pro", heroTitleLead: "온라인 도구", heroSubtitle: "{client}+ 무료. AI {aiLimit}/일 — Pro 무제한.", footerNote: "{client}+ 무료 · Pro 무제한", homeValueFreeTitle: "무료", homeValueFreeDesc: "{client}+ · AI {aiLimit}/일", homeCtaSubtitle: "{client}+ 가입 불필요. Pro 언제든." } },
  ru: { nav: { categories: "Категории", allTools: "Все инструменты", pricing: "Цены", search: "Поиск", menu: "Меню", toolsCount: "{n} инстр." }, auth: { signIn: "Войти", signOut: "Выйти", managePro: "Управление Pro", upgradePro: "Перейти на Pro" }, home: { explore: "Обзор", pickCategory: "Выберите категорию", pickCategorySub: "{n}+ инструментов для вас.", seeAll: "Все", trending: "В тренде", trendingTitle: "Популярное сейчас", valuePrivate: "Приватно", valuePrivateDesc: "В браузере", valueInstant: "Мгновенно", valueInstantDesc: "Без ожидания", valueOnline: "Онлайн", valueOnlineDesc: "Везде", ctaTitle: "Начать сейчас", browseAll: "Все инструменты", searchAll: "Поиск", heroEverything: "всё", heroYouDo: "что делаете.", searchPlaceholder: "Поиск {n}+ инстр…", go: "Go", allToolsArrow: "Все →", toolsInCategory: "{n} инстр." }, footer: { allTools: "Все", pricing: "Цены", about: "О нас", privacy: "Конфиденциальность", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Страница или инструмент не найдены.", goHome: "Главная", browseTools: "Инструменты" }, copy: { tagline: "{n}+ онлайн-инструментов", taglineWithTier: "{n}+ · Бесплатно + Pro", siteDescription: "{total}+ инстр. в {cats} категориях. {client}+ бесплатно в браузере. AI: {aiLimit}/день — Pro безлимит.", heroBadge: "{n}+ · Бесплатно + Pro", heroTitleLead: "Онлайн-инструменты для", heroSubtitle: "{client}+ бесплатно. AI: {aiLimit}/день — Pro безлимит.", footerNote: "{client}+ бесплатно · Pro безлимит", homeValueFreeTitle: "Бесплатно", homeValueFreeDesc: "{client}+ · AI {aiLimit}/день", homeCtaSubtitle: "{client}+ без регистрации. Pro в любое время." } },
  tr: { nav: { categories: "Kategoriler", allTools: "Tüm Araçlar", pricing: "Fiyatlar", search: "Ara", menu: "Menü", toolsCount: "{n} araç" }, auth: { signIn: "Giriş", signOut: "Çıkış", managePro: "Pro Yönet", upgradePro: "Pro'ya Geç" }, home: { explore: "Keşfet", pickCategory: "Kategori seç", pickCategorySub: "{n}+ araç, sizin için.", seeAll: "Tümü", trending: "Trend", trendingTitle: "Şu an popüler", valuePrivate: "Gizli", valuePrivateDesc: "Tarayıcıda çalışır", valueInstant: "Anında", valueInstantDesc: "Bekleme yok", valueOnline: "Çevrimiçi", valueOnlineDesc: "Her yerde", ctaTitle: "Hemen kullanın", browseAll: "Tüm araçlar", searchAll: "Ara", heroEverything: "her şey", heroYouDo: "için.", searchPlaceholder: "{n}+ araç ara…", go: "Git", allToolsArrow: "Tümü →", toolsInCategory: "{n} araç" }, footer: { allTools: "Tüm Araçlar", pricing: "Fiyatlar", about: "Hakkında", privacy: "Gizlilik", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Sayfa veya araç bulunamadı.", goHome: "Ana sayfa", browseTools: "Araçlar" }, copy: { tagline: "{n}+ çevrimiçi araç", taglineWithTier: "{n}+ · Ücretsiz + Pro", siteDescription: "{cats} kategoride {total}+ araç. {client}+ ücretsiz. AI: {aiLimit}/gün — Pro sınırsız.", heroBadge: "{n}+ · Ücretsiz + Pro", heroTitleLead: "Çevrimiçi araçlar", heroSubtitle: "{client}+ ücretsiz. AI: {aiLimit}/gün — Pro sınırsız.", footerNote: "{client}+ ücretsiz · Pro sınırsız", homeValueFreeTitle: "Ücretsiz", homeValueFreeDesc: "{client}+ · AI {aiLimit}/gün", homeCtaSubtitle: "{client}+ kayıtsız. Pro istediğiniz zaman." } },
  id: { nav: { categories: "Kategori", allTools: "Semua Alat", pricing: "Harga", search: "Cari", menu: "Menu", toolsCount: "{n} alat" }, auth: { signIn: "Masuk", signOut: "Keluar", managePro: "Kelola Pro", upgradePro: "Upgrade Pro" }, home: { explore: "Jelajahi", pickCategory: "Pilih kategori", pickCategorySub: "{n}+ alat untuk Anda.", seeAll: "Semua", trending: "Trending", trendingTitle: "Paling populer", valuePrivate: "Privat", valuePrivateDesc: "Di browser", valueInstant: "Instan", valueInstantDesc: "Tanpa tunggu", valueOnline: "Online", valueOnlineDesc: "Di mana saja", ctaTitle: "Mulai sekarang", browseAll: "Semua alat", searchAll: "Cari", heroEverything: "semua", heroYouDo: "yang Anda lakukan.", searchPlaceholder: "Cari {n}+ alat…", go: "Go", allToolsArrow: "Semua →", toolsInCategory: "{n} alat" }, footer: { allTools: "Semua Alat", pricing: "Harga", about: "Tentang", privacy: "Privasi", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Halaman atau alat tidak ditemukan.", goHome: "Beranda", browseTools: "Jelajahi alat" }, copy: { tagline: "{n}+ alat online", taglineWithTier: "{n}+ · Gratis + Pro", siteDescription: "{total}+ alat di {cats} kategori. {client}+ gratis di browser. AI: {aiLimit}/hari — Pro tanpa batas.", heroBadge: "{n}+ · Gratis + Pro", heroTitleLead: "Alat online untuk", heroSubtitle: "{client}+ gratis. AI: {aiLimit}/hari — Pro tanpa batas.", footerNote: "{client}+ gratis · Pro tanpa batas", homeValueFreeTitle: "Gratis", homeValueFreeDesc: "{client}+ · AI {aiLimit}/hari", homeCtaSubtitle: "{client}+ tanpa daftar. Upgrade Pro kapan saja." } },
});

// Fill remaining locales from English template + category names
for (const code of ["fa", "ps", "bn", "pa", "ms", "it", "nl", "uk", "pl", "vi", "th", "tl"]) {
  if (!LOCALES[code]) LOCALES[code] = structuredClone(LOCALES.en);
}

// Override UI for remaining locales (compact)
const MORE = {
  fa: { nav: { categories: "دسته‌ها", allTools: "همه ابزارها", pricing: "قیمت", search: "جستجو", menu: "منو", toolsCount: "{n} ابزار" }, auth: { signIn: "ورود", signOut: "خروج", managePro: "مدیریت Pro", upgradePro: "ارتقا به Pro" }, home: { explore: "کاوش", pickCategory: "دسته انتخاب کنید", pickCategorySub: "{n}+ ابزار برای شما.", seeAll: "همه", trending: "پرطرفدار", trendingTitle: "محبوب‌ترین", valuePrivate: "خصوصی", valuePrivateDesc: "در مرورگر", valueInstant: "فوری", valueInstantDesc: "بدون انتظار", valueOnline: "آنلاین", valueOnlineDesc: "همه‌جا", ctaTitle: "همین now شروع کنید", browseAll: "همه ابزارها", searchAll: "جستجو", heroEverything: "همه", heroYouDo: "کارها.", searchPlaceholder: "جستجوی {n}+ ابزار…", go: "برو", allToolsArrow: "همه ←", toolsInCategory: "{n} ابزار" }, footer: { allTools: "همه", pricing: "قیمت", about: "درباره", privacy: "حریم خصوصی", copyright: "© {year} {name}" }, notFound: { title: "404", message: "صفحه یا ابزار یافت نشد.", goHome: "خانه", browseTools: "ابزارها" }, copy: { tagline: "{n}+ ابزار آنلاین", taglineWithTier: "{n}+ · رایگان + Pro", siteDescription: "{total}+ ابزار در {cats} دسته. {client}+ رایگان. AI: {aiLimit}/روز — Pro نامحدود.", heroBadge: "{n}+ · رایگان + Pro", heroTitleLead: "ابزار آنلاین برای", heroSubtitle: "{client}+ رایگان. AI: {aiLimit}/روز — Pro نامحدود.", footerNote: "{client}+ رایگان · Pro نامحدود", homeValueFreeTitle: "رایگان", homeValueFreeDesc: "{client}+ · AI {aiLimit}/روز", homeCtaSubtitle: "{client}+ بدون ثبت‌نام. Pro هر زمان." } },
  it: { nav: { categories: "Categorie", allTools: "Tutti gli strumenti", pricing: "Prezzi", search: "Cerca", menu: "Menu", toolsCount: "{n} strumenti" }, auth: { signIn: "Accedi", signOut: "Esci", managePro: "Gestisci Pro", upgradePro: "Passa a Pro" }, home: { explore: "Esplora", pickCategory: "Scegli categoria", pickCategorySub: "{n}+ strumenti per te.", seeAll: "Vedi tutti", trending: "Di tendenza", trendingTitle: "Più popolari", valuePrivate: "Privato", valuePrivateDesc: "Nel browser", valueInstant: "Istantaneo", valueInstantDesc: "Senza attesa", valueOnline: "Online", valueOnlineDesc: "Ovunque", ctaTitle: "Inizia ora", browseAll: "Tutti gli strumenti", searchAll: "Cerca", heroEverything: "tutto", heroYouDo: "ciò che fai.", searchPlaceholder: "Cerca {n}+ strumenti…", go: "Vai", allToolsArrow: "Tutti →", toolsInCategory: "{n} strumenti" }, footer: { allTools: "Tutti", pricing: "Prezzi", about: "Info", privacy: "Privacy", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Pagina o strumento non trovato.", goHome: "Home", browseTools: "Strumenti" }, copy: { tagline: "{n}+ strumenti online", taglineWithTier: "{n}+ · Gratis + Pro", siteDescription: "{total}+ strumenti in {cats} categorie. {client}+ gratis. AI: {aiLimit}/giorno — Pro illimitato.", heroBadge: "{n}+ · Gratis + Pro", heroTitleLead: "Strumenti online per", heroSubtitle: "{client}+ gratis. AI: {aiLimit}/giorno — Pro illimitato.", footerNote: "{client}+ gratis · Pro illimitato", homeValueFreeTitle: "Gratis", homeValueFreeDesc: "{client}+ · AI {aiLimit}/giorno", homeCtaSubtitle: "{client}+ senza registrazione. Pro quando vuoi." } },
  nl: { nav: { categories: "Categorieën", allTools: "Alle tools", pricing: "Prijzen", search: "Zoeken", menu: "Menu", toolsCount: "{n} tools" }, auth: { signIn: "Inloggen", signOut: "Uitloggen", managePro: "Pro beheren", upgradePro: "Upgrade naar Pro" }, home: { explore: "Ontdekken", pickCategory: "Kies categorie", pickCategorySub: "{n}+ tools voor jou.", seeAll: "Alles", trending: "Trending", trendingTitle: "Meest populair", valuePrivate: "Privé", valuePrivateDesc: "In je browser", valueInstant: "Direct", valueInstantDesc: "Geen wachten", valueOnline: "Online", valueOnlineDesc: "Overal", ctaTitle: "Begin nu", browseAll: "Alle tools", searchAll: "Zoeken", heroEverything: "alles", heroYouDo: "wat je doet.", searchPlaceholder: "Zoek {n}+ tools…", go: "Ga", allToolsArrow: "Alle →", toolsInCategory: "{n} tools" }, footer: { allTools: "Alle tools", pricing: "Prijzen", about: "Over", privacy: "Privacy", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Pagina of tool niet gevonden.", goHome: "Home", browseTools: "Tools" }, copy: { tagline: "{n}+ online tools", taglineWithTier: "{n}+ · Gratis + Pro", siteDescription: "{total}+ tools in {cats} categorieën. {client}+ gratis. AI: {aiLimit}/dag — Pro onbeperkt.", heroBadge: "{n}+ · Gratis + Pro", heroTitleLead: "Online tools voor", heroSubtitle: "{client}+ gratis. AI: {aiLimit}/dag — Pro onbeperkt.", footerNote: "{client}+ gratis · Pro onbeperkt", homeValueFreeTitle: "Gratis", homeValueFreeDesc: "{client}+ · AI {aiLimit}/dag", homeCtaSubtitle: "{client}+ zonder account. Pro wanneer je wilt." } },
  vi: { nav: { categories: "Danh mục", allTools: "Tất cả công cụ", pricing: "Giá", search: "Tìm", menu: "Menu", toolsCount: "{n} công cụ" }, auth: { signIn: "Đăng nhập", signOut: "Đăng xuất", managePro: "Quản lý Pro", upgradePro: "Nâng cấp Pro" }, home: { explore: "Khám phá", pickCategory: "Chọn danh mục", pickCategorySub: "{n}+ công cụ cho bạn.", seeAll: "Xem tất cả", trending: "Xu hướng", trendingTitle: "Phổ biến nhất", valuePrivate: "Riêng tư", valuePrivateDesc: "Trên trình duyệt", valueInstant: "Tức thì", valueInstantDesc: "Không chờ", valueOnline: "Trực tuyến", valueOnlineDesc: "Mọi nơi", ctaTitle: "Bắt đầu ngay", browseAll: "Tất cả công cụ", searchAll: "Tìm kiếm", heroEverything: "mọi", heroYouDo: "việc.", searchPlaceholder: "Tìm {n}+ công cụ…", go: "Đi", allToolsArrow: "Tất cả →", toolsInCategory: "{n} công cụ" }, footer: { allTools: "Tất cả", pricing: "Giá", about: "Giới thiệu", privacy: "Riêng tư", copyright: "© {year} {name}" }, notFound: { title: "404", message: "Không tìm thấy trang hoặc công cụ.", goHome: "Trang chủ", browseTools: "Công cụ" }, copy: { tagline: "{n}+ công cụ trực tuyến", taglineWithTier: "{n}+ · Miễn phí + Pro", siteDescription: "{total}+ công cụ, {cats} danh mục. {client}+ miễn phí. AI: {aiLimit}/ngày — Pro không giới hạn.", heroBadge: "{n}+ · Miễn phí + Pro", heroTitleLead: "Công cụ trực tuyến cho", heroSubtitle: "{client}+ miễn phí. AI: {aiLimit}/ngày — Pro không giới hạn.", footerNote: "{client}+ miễn phí · Pro không giới hạn", homeValueFreeTitle: "Miễn phí", homeValueFreeDesc: "{client}+ · AI {aiLimit}/ngày", homeCtaSubtitle: "{client}+ không cần đăng ký. Pro bất cứ lúc nào." } },
  th: { nav: { categories: "หมวดหมู่", allTools: "เครื่องมือทั้งหมด", pricing: "ราคา", search: "ค้นหา", menu: "เมนู", toolsCount: "{n} เครื่องมือ" }, auth: { signIn: "เข้าสู่ระบบ", signOut: "ออก", managePro: "จัดการ Pro", upgradePro: "อัปเกรด Pro" }, home: { explore: "สำรวจ", pickCategory: "เลือกหมวด", pickCategorySub: "{n}+ เครื่องมือสำหรับคุณ", seeAll: "ทั้งหมด", trending: "มาแรง", trendingTitle: "ยอดนิยม", valuePrivate: "ส่วนตัว", valuePrivateDesc: "ในเบราว์เซอร์", valueInstant: "ทันที", valueInstantDesc: "ไม่ต้องรอ", valueOnline: "ออนไลน์", valueOnlineDesc: "ทุกที่", ctaTitle: "เริ่มใช้เลย", browseAll: "เครื่องมือทั้งหมด", searchAll: "ค้นหา", heroEverything: "ทุก", heroYouDo: "สิ่งที่ทำ", searchPlaceholder: "ค้นหา {n}+ …", go: "ไป", allToolsArrow: "ทั้งหมด →", toolsInCategory: "{n} เครื่องมือ" }, footer: { allTools: "ทั้งหมด", pricing: "ราคา", about: "เกี่ยวกับ", privacy: "ความเป็นส่วนตัว", copyright: "© {year} {name}" }, notFound: { title: "404", message: "ไม่พบหน้าหรือเครื่องมือ", goHome: "หน้าแรก", browseTools: "เครื่องมือ" }, copy: { tagline: "{n}+ เครื่องมือออนไลน์", taglineWithTier: "{n}+ · ฟรี + Pro", siteDescription: "{total}+ เครื่องมือ {cats} หมวด {client}+ ฟรี AI {aiLimit}/วัน — Pro ไม่จำกัด", heroBadge: "{n}+ · ฟรี + Pro", heroTitleLead: "เครื่องมือออนไลน์สำหรับ", heroSubtitle: "{client}+ ฟรี AI {aiLimit}/วัน — Pro ไม่จำกัด", footerNote: "{client}+ ฟree · Pro ไม่จำกัด", homeValueFreeTitle: "ฟรี", homeValueFreeDesc: "{client}+ · AI {aiLimit}/วัน", homeCtaSubtitle: "{client}+ ไม่ต้องสมัคร Pro ได้ทุกเมื่อ" } },
};
Object.assign(LOCALES, MORE);

const LOCALE_CODES = ["en", "ur", "fr", "de"];
for (const code of LOCALE_CODES) {
  const data = { ...LOCALES[code], categories: cats(code) };
  writeFileSync(join(outDir, `${code}.json`), JSON.stringify(data, null, 2) + "\n");
  console.log("✓", code);
}
console.log(`\n${LOCALE_CODES.length} locales → ${outDir}`);
