/** Built by scripts/generate-tool-blogs.mjs. Maps category/slug to the guide post. */
export const TOOL_GUIDES: Record<string, { slug: string; title: string }> = {
  "ai-tools/ai-form-builder": { slug: "ai-form-builder-guide", title: "AI Form Builder: 60+ ready-made forms from any country, or describe a custom form in any language. Edit, brand, sign, scan from image, downl" },
  "ai-tools/ats-resume-checker": { slug: "ats-resume-checker-guide", title: "ATS Resume Checker: Upload a CV and a job ad — see ATS parseability, keyword match, and a detailed issue list with fixes" },
  "ai-tools/code-explainer": { slug: "github-copilot-vs-cursor", title: "GitHub Copilot vs Cursor — Which AI Coding Tool Should You Pay For?" },
  "ai-tools/code-review-assistant": { slug: "code-review-assistant-guide", title: "AI Code Review Assistant: Get feedback on your code split into Security, Performance and Style sections" },
  "ai-tools/commit-message-generator": { slug: "commit-message-generator-guide", title: "AI Commit Message Generator: Turn a git diff into a clean commit message — Conventional Commits, Gitmoji or plain style" },
  "ai-tools/cover-letter-generator": { slug: "ai-cover-letter-generator-guide", title: "How to Write a Cover Letter That Gets Interviews (With Free AI)" },
  "ai-tools/cron-explainer": { slug: "cron-explainer-guide", title: "AI Cron Expression Explainer: Convert plain English to a cron expression or explain any cron expression, with timezone-aware next run times" },
  "ai-tools/docker-compose-generator": { slug: "docker-compose-generator-guide", title: "AI Docker Compose Generator: Describe your services or pick a stack template (MERN, Laravel+MySQL+Redis, Django+Postgres) and get a valid do" },
  "ai-tools/error-diagnoser": { slug: "error-diagnoser-guide", title: "AI Error Diagnoser: Paste an error or stack trace and get the root cause plus the exact code fix as a diff" },
  "ai-tools/interview-answer-generator": { slug: "ai-interview-answer-generator-guide", title: "How to Answer Interview Questions With STAR (Without Sounding Scripted)" },
  "ai-tools/pr-description-generator": { slug: "ai-pr-description-generator-guide", title: "How to Write Pull Request Descriptions Reviewers Actually Read" },
  "ai-tools/readme-generator": { slug: "readme-generator-guide", title: "AI README Generator: Generate a professional README.md from your project details, auto-detecting the stack from package.json" },
  "ai-tools/regex-generator": { slug: "regex-generator-guide", title: "AI Regex Generator: Turn a plain-English description into a working regular expression, with an explanation and examples" },
  "ai-tools/sql-query-generator": { slug: "sql-query-generator-guide", title: "AI SQL Query Generator: Describe a query in English and get correct SQL for Postgres, MySQL, SQLite or T-SQL, explained back to you" },
  "ai-tools/test-case-generator": { slug: "test-case-generator-guide", title: "Test Case Generator: Paste a function and get a thorough test suite for Jest, PyTest or JUnit covering edge cases" },
  "calculators/afghan-date-converter": { slug: "afghan-date-converter-guide", title: "Afghan Date Converter: Convert Shamsi (Solar Hijri) dates to Gregorian and back" },
  "calculators/age-calculator": { slug: "square-footage-calculator-guide", title: "Square Footage Calculator for Rooms, Circles, and Odd Lots" },
  "calculators/apr-calculator": { slug: "apr-vs-interest-rate-calculator", title: "APR Calculator — Why APR Is Higher Than the Interest Rate" },
  "calculators/bmi-calculator": { slug: "bmi-calculator-guide", title: "BMI Calculator: Calculate Body Mass Index from height and weight in metric or imperial units" },
  "calculators/bmr-calculator": { slug: "bmr-calculator-guide", title: "BMR Calculator: Calculate Basal Metabolic Rate to estimate resting calorie burn" },
  "calculators/body-fat-calculator": { slug: "body-fat-calculator-guide", title: "Body Fat Calculator: Estimate body fat percentage using the US Navy method measurements" },
  "calculators/cagr-calculator": { slug: "cagr-calculator-explained", title: "CAGR Explained — How to Calculate Compound Annual Growth Rate" },
  "calculators/calorie-calculator": { slug: "calorie-calculator-guide", title: "Calorie Calculator: Estimate daily calorie needs for maintenance, loss, or gain" },
  "calculators/compound-interest-calculator": { slug: "compound-interest-calculator-guide", title: "Compound Interest Calculator: Project investment growth with compounding over time and contributions" },
  "calculators/concrete-calculator": { slug: "concrete-calculator-yards-and-bags", title: "Concrete Calculator — Cubic Yards, Bags, and Waste for a Slab" },
  "calculators/countdown-calculator": { slug: "countdown-calculator-guide", title: "Countdown Calculator: Count down the days, hours, and minutes until any target date" },
  "calculators/credit-card-payoff-calculator": { slug: "credit-card-payoff-calculator-guide", title: "Credit Card Payoff Calculator — Months, Interest, and Extra Payments" },
  "calculators/date-calculator": { slug: "date-calculator-guide", title: "Date Calculator: Add or subtract days from a date and find the span between two dates" },
  "calculators/debt-payoff-calculator": { slug: "debt-payoff-calculator-guide", title: "Debt Payoff Calculator: Compare snowball vs avalanche debt payoff plans with months, interest, and a payment schedule" },
  "calculators/debt-to-income-calculator": { slug: "debt-to-income-ratio-calculator-guide", title: "Debt-to-Income Ratio Calculator — Front-End and Back-End DTI" },
  "calculators/discount-calculator": { slug: "discount-calculator-guide", title: "Discount Calculator: Find sale price and amount saved from an original price and discount percent" },
  "calculators/due-date-calculator": { slug: "due-date-calculator-guide", title: "Due Date Calculator: Estimate a pregnancy due date from the last menstrual period" },
  "calculators/emi-calculator": { slug: "emi-calculator-explained", title: "EMI Explained — Calculate Loan Payments Before You Borrow" },
  "calculators/epf-calculator": { slug: "epf-calculator-guide", title: "EPF Calculator Explained — Estimate Your Provident Fund Maturity" },
  "calculators/fd-calculator": { slug: "fd-calculator-explained", title: "FD Calculator Explained — How to Calculate Fixed Deposit Maturity" },
  "calculators/fraction-calculator": { slug: "fraction-calculator-guide", title: "Fraction Calculator: Add, subtract, multiply, and simplify fractions" },
  "calculators/fuel-cost-calculator": { slug: "fuel-cost-calculator-trip-mpg", title: "Fuel Cost Calculator — Trip Gallons, MPG, and Cost per Person" },
  "calculators/gpa-calculator": { slug: "gpa-calculator-guide", title: "GPA Calculator: Compute grade point average from course grades and credit hours" },
  "calculators/grade-calculator": { slug: "grade-calculator-guide", title: "Grade Calculator: Calculate final or weighted grades and the score needed to pass" },
  "calculators/gratuity-calculator": { slug: "gratuity-calculator-guide", title: "Gratuity Calculator Explained — Estimate Your Exit Payout" },
  "calculators/gravel-calculator": { slug: "gravel-calculator-tons-and-yards", title: "Gravel Calculator — Cubic Yards and Tons for a Driveway or Path" },
  "calculators/home-affordability-calculator": { slug: "home-affordability-calculator-guide", title: "Home Affordability Calculator — Max Price from Income and Debts" },
  "calculators/hours-calculator": { slug: "hours-calculator-guide", title: "Hours Calculator: Calculate total hours and minutes between two times for timesheets" },
  "calculators/hra-calculator": { slug: "hra-calculator-guide", title: "HRA Calculator Explained — Estimate Your House Rent Allowance Exemption" },
  "calculators/ideal-weight-calculator": { slug: "ideal-weight-calculator-guide", title: "Ideal Weight Calculator: Suggest a healthy weight range based on height, age, and gender" },
  "calculators/inflation-calculator": { slug: "inflation-calculator-guide", title: "Inflation Calculator: See what today’s money will be worth later — or was worth in the past — using a custom inflation rate" },
  "calculators/loan-calculator": { slug: "loan-calculator-guide", title: "Loan Calculator: Estimate monthly payments, total interest, and payoff for any loan" },
  "calculators/lumpsum-calculator": { slug: "lumpsum-calculator-guide", title: "Lumpsum Calculator Guide — Estimate One-Time Mutual Fund Growth" },
  "calculators/mortgage-calculator": { slug: "mortgage-piti-calculator-guide", title: "Mortgage Calculator — PITI, PMI, and 15-Year vs 30-Year Cost" },
  "calculators/nps-calculator": { slug: "nps-calculator-guide", title: "NPS Calculator Explained — Estimate Your National Pension Corpus" },
  "calculators/nsc-calculator": { slug: "nsc-calculator-guide", title: "NSC Calculator Guide — Estimate National Savings Certificate Maturity" },
  "calculators/ovulation-calculator": { slug: "ovulation-calculator-guide", title: "Ovulation Calculator: Predict fertile windows and ovulation days from cycle data" },
  "calculators/paint-calculator": { slug: "paint-calculator-how-many-gallons", title: "Paint Calculator — How Many Gallons a Room Actually Needs" },
  "calculators/paycheck-calculator": { slug: "paycheck-calculator-guide", title: "Paycheck Calculator: Estimate take-home pay after taxes and common deductions" },
  "calculators/percentage-calculator": { slug: "percentage-calculator-guide", title: "Percentage Calculator: Find percentages, percentage change, and what percent one number is of another" },
  "calculators/ppf-calculator": { slug: "ppf-calculator-guide", title: "PPF Calculator Guide — Estimate Public Provident Fund Maturity" },
  "calculators/pregnancy-calculator": { slug: "pregnancy-calculator-guide", title: "Pregnancy Calculator: Track pregnancy progress, week count, and key milestones" },
  "calculators/profit-margin-calculator": { slug: "profit-margin-calculator-guide", title: "Profit Margin Calculator: Calculate profit, profit margin %, and markup from cost and selling price" },
  "calculators/random-number-generator": { slug: "random-number-generator-guide", title: "Random Number Generator: Generate random numbers within a custom range with options" },
  "calculators/rd-calculator": { slug: "rd-calculator-guide", title: "RD Calculator Guide — Estimate Recurring Deposit Maturity Before You Save" },
  "calculators/roi-calculator": { slug: "roi-calculator-guide", title: "ROI Calculator Guide — Measure Return on Investment Clearly" },
  "calculators/salary-calculator": { slug: "salary-calculator-guide", title: "Salary Calculator: Convert pay between hourly, weekly, monthly, and annual rates" },
  "calculators/salary-tax-calculator": { slug: "salary-tax-calculator-guide", title: "Salary Tax Calculator: Estimate income tax and net salary from gross pay" },
  "calculators/sales-tax-calculator": { slug: "sales-tax-calculator-guide", title: "Sales Tax Calculator: Add sales tax to a price or extract tax from a gross amount" },
  "calculators/scientific-calculator": { slug: "scientific-calculator-guide", title: "Scientific Calculator: Full-function calculator with trig, logs, exponents, and constants" },
  "calculators/scss-calculator": { slug: "scss-calculator-guide", title: "SCSS Calculator Guide — Estimate Senior Citizen Savings Scheme Interest" },
  "calculators/sip-calculator": { slug: "sip-calculator-guide", title: "SIP Calculator Guide — Estimate Mutual Fund Returns Before You Invest" },
  "calculators/sleep-calculator": { slug: "sleep-calculator-guide", title: "Sleep Calculator: Suggest bedtimes or wake times based on 90-minute sleep cycles" },
  "calculators/square-footage-calculator": { slug: "square-footage-calculator-guide", title: "Square Footage Calculator for Rooms, Circles, and Odd Lots" },
  "calculators/ssy-calculator": { slug: "ssy-calculator-guide", title: "SSY Calculator Guide — Estimate Sukanya Samriddhi Yojana Maturity" },
  "calculators/standard-deviation-calculator": { slug: "standard-deviation-calculator-guide", title: "Standard Deviation Calculator: Compute mean, variance, and standard deviation for a data set" },
  "calculators/swp-calculator": { slug: "swp-calculator-guide", title: "SWP Calculator Guide — Plan Monthly Mutual Fund Withdrawals" },
  "calculators/tasbih-counter": { slug: "tasbih-counter-guide", title: "Tasbih Counter: Digital Tasbih counter for dhikr and Islamic remembrance" },
  "calculators/tdee-calculator": { slug: "tdee-calculator-guide", title: "TDEE Calculator: Compute Total Daily Energy Expenditure from BMR and activity level" },
  "calculators/time-duration-calculator": { slug: "time-duration-calculator-guide", title: "Time Duration Calculator: Measure elapsed time between two date-times in multiple units" },
  "calculators/tip-calculator": { slug: "tip-calculator-guide", title: "Tip Calculator: Calculate tip amount and split the total bill among multiple people" },
  "calculators/vat-gst-calculator": { slug: "vat-gst-calculator-guide", title: "VAT / GST Calculator: Add or extract VAT and GST from any amount with a custom tax rate" },
  "calculators/xirr-calculator": { slug: "xirr-calculator-guide", title: "XIRR Calculator Guide — Annualized Return for Irregular Cash Flows" },
  "calculators/zakat-calculator": { slug: "zakat-calculator-guide", title: "Zakat Calculator: Calculate Zakat on gold, silver and wealth in your browser" },
  "color-tools/analogous-color-generator": { slug: "analogous-color-generator-guide", title: "Analogous Color Generator: Generate analogous color schemes from a base color" },
  "color-tools/box-shadow-generator": { slug: "box-shadow-generator-guide", title: "Box Shadow Generator: Build and preview CSS box-shadow code" },
  "color-tools/cmyk-to-rgb": { slug: "cmyk-to-rgb-guide", title: "CMYK to RGB: Convert CMYK print colors back to RGB" },
  "color-tools/color-blindness-simulator": { slug: "color-blindness-simulator-guide", title: "Color Blindness Simulator: Preview colors as seen with color vision deficiencies" },
  "color-tools/color-contrast-checker": { slug: "color-contrast-checker-guide", title: "Color Contrast Checker: Check WCAG contrast ratio between two colors" },
  "color-tools/color-from-image": { slug: "color-from-image-guide", title: "Color from Image: Pick and extract colors directly from an uploaded image" },
  "color-tools/color-mixer": { slug: "color-mixer-guide", title: "Color Mixer: Blend two colors and preview the mixed result" },
  "color-tools/color-name-finder": { slug: "color-name-finder-guide", title: "Color Name Finder: Find the closest named color for any HEX value" },
  "color-tools/color-palette-generator": { slug: "color-palette-generator-guide", title: "Color Palette Generator: Generate harmonious color palettes instantly" },
  "color-tools/color-picker": { slug: "color-picker-guide", title: "Color Picker: Pick any color and get its HEX, RGB, and HSL values" },
  "color-tools/color-shades-generator": { slug: "color-shades-generator-guide", title: "Color Shades Generator: Generate darker shades of a base color" },
  "color-tools/color-tints-generator": { slug: "color-tints-generator-guide", title: "Color Tints Generator: Generate lighter tints of a base color" },
  "color-tools/color-wheel": { slug: "color-wheel-guide", title: "Color Wheel: Explore complementary and harmony colors on a wheel" },
  "color-tools/complementary-color-finder": { slug: "complementary-color-finder-guide", title: "Complementary Color Finder: Find the complementary color for any input color" },
  "color-tools/css-gradient-background-generator": { slug: "css-gradient-background-generator-guide", title: "CSS Gradient Background Generator: Generate copy-paste CSS gradient backgrounds" },
  "color-tools/gradient-generator": { slug: "gradient-generator-guide", title: "Gradient Generator: Build CSS linear and radial gradients visually" },
  "color-tools/hex-color-to-image": { slug: "hex-color-to-image-guide", title: "Hex Color to Image: Generate a solid color image from a HEX code" },
  "color-tools/hex-to-cmyk": { slug: "hex-to-cmyk-guide", title: "HEX to CMYK: Convert a HEX color code to CMYK values" },
  "color-tools/hex-to-hsl": { slug: "hex-to-hsl-guide", title: "HEX to HSL: Convert HEX colors to HSL format" },
  "color-tools/hex-to-rgb": { slug: "hex-to-rgb-guide", title: "HEX to RGB: Convert HEX color codes to RGB values" },
  "color-tools/hex-to-rgba": { slug: "hex-to-rgba-guide", title: "Hex to RGBA: Convert HEX colors to RGBA with an alpha channel" },
  "color-tools/hsl-to-hex": { slug: "hsl-to-hex-guide", title: "HSL to HEX: Convert HSL color values to a HEX code" },
  "color-tools/lighten-darken-color": { slug: "lighten-darken-color-guide", title: "Lighten and Darken Color: Adjust a color's lightness up or down by percentage" },
  "color-tools/monochromatic-color-generator": { slug: "monochromatic-color-generator-guide", title: "Monochromatic Color Generator: Build a single-hue monochromatic palette" },
  "color-tools/random-color-generator": { slug: "random-color-generator-guide", title: "Random Color Generator: Generate random colors with their codes" },
  "color-tools/rgb-to-cmyk": { slug: "rgb-to-cmyk-guide", title: "RGB to CMYK: Convert RGB colors to CMYK for printing" },
  "color-tools/rgb-to-hex": { slug: "rgb-to-hex-guide", title: "RGB to HEX: Convert RGB values to a HEX color code" },
  "color-tools/rgb-to-hsl": { slug: "rgb-to-hsl-guide", title: "RGB to HSL: Convert RGB color values to HSL" },
  "color-tools/text-shadow-generator": { slug: "text-shadow-generator-guide", title: "Text Shadow Generator: Create CSS text-shadow effects with live preview" },
  "color-tools/triadic-color-generator": { slug: "triadic-color-generator-guide", title: "Triadic Color Generator: Create triadic three-color harmony schemes" },
  "content-creator-tools/online-video-editor": { slug: "online-video-editor-guide", title: "Online Video Editor: Edit videos in the browser — multi-clip timeline, trim/split/reverse, transitions, filters, FX, captions + SRT, logos, " },
  "content-creator-tools/text-to-speech": { slug: "elevenlabs-vs-browser-text-to-speech", title: "ElevenLabs vs Browser Text to Speech — Paid AI Voice or Free Device Voices?" },
  "content-creator-tools/video-script-studio": { slug: "video-script-studio-guide", title: "Video Script Studio: Upload any video → extract script, scene-by-scene remake plan, free stock B-roll links, and matching voiceover. Works f" },
  "converters-generators/barcode-generator": { slug: "barcode-generator-guide", title: "Barcode Generator: Create barcodes in formats like Code128, EAN, and UPC" },
  "converters-generators/code-minifier": { slug: "code-minifier-guide", title: "Code Minifier: Minify HTML, CSS, and JavaScript to reduce file size" },
  "converters-generators/color-converter": { slug: "color-converter-guide", title: "Color Converter (HEX / RGB / HSL): Convert colors between HEX, RGB, HSL, and HSV" },
  "converters-generators/csv-to-tsv": { slug: "csv-to-tsv-guide", title: "CSV to TSV Converter: Convert CSV to TSV and Excel-friendly formats" },
  "converters-generators/decision-wheel": { slug: "decision-wheel-guide", title: "Decision Wheel: Spin a colorful wheel to pick randomly from your list — lunch, chores, team decisions, and more" },
  "converters-generators/email-signature-generator": { slug: "email-signature-generator-guide", title: "Email Signature Generator: Create a professional HTML email signature with name, title, contact, and brand color" },
  "converters-generators/hash-generator": { slug: "hash-generator-guide", title: "Hash Generator (MD5 / SHA): Compute MD5, SHA-1, and SHA-256 hashes of text" },
  "converters-generators/html-to-markdown": { slug: "html-to-markdown-guide", title: "HTML to Markdown Converter: Convert HTML markup into clean Markdown" },
  "converters-generators/iban-validator": { slug: "iban-validator-guide", title: "IBAN Validator: Validate IBAN numbers for Pakistan, EU, UK and 80+ countries with mod-97 checksum" },
  "converters-generators/ics-calendar-generator": { slug: "ics-calendar-generator-guide", title: "ICS Calendar Generator: Build a .ics calendar event file for Google Calendar, Outlook, and Apple Calendar" },
  "converters-generators/invoice-generator": { slug: "invoice-generator-guide", title: "Invoice Generator: Create professional PDF invoices with line items, tax, and instant download — no watermark" },
  "converters-generators/json-to-typescript": { slug: "json-to-typescript-guide", title: "JSON to TypeScript: Generate TypeScript interfaces from a JSON sample" },
  "converters-generators/json-to-xml": { slug: "json-to-xml-guide", title: "JSON to XML Converter: Convert JSON data structures into XML" },
  "converters-generators/list-randomizer": { slug: "list-randomizer-guide", title: "List Randomizer: Shuffle or pick random items from a pasted list" },
  "converters-generators/markdown-to-html": { slug: "markdown-to-html-guide", title: "Markdown to HTML Converter: Render Markdown into HTML with live preview" },
  "converters-generators/pomodoro-timer": { slug: "pomodoro-timer-guide", title: "Pomodoro Timer: Free focus timer with 25-minute Pomodoros, short/long breaks, task label, and optional alerts" },
  "converters-generators/random-string-generator": { slug: "random-string-generator-guide", title: "Random String Generator: Generate random strings and API tokens with custom charsets" },
  "converters-generators/sql-to-json": { slug: "sql-to-json-guide", title: "SQL to JSON Converter: Convert SQL INSERT statements into JSON or CSV" },
  "converters-generators/vcard-generator": { slug: "vcard-generator-guide", title: "vCard Generator: Generate a downloadable .vcf contact card for phones and email clients" },
  "converters-generators/xml-to-json": { slug: "xml-to-json-guide", title: "XML to JSON Converter: Parse XML into JSON and back" },
  "developer-tools/base64-encoder-decoder": { slug: "base64-encoder-decoder-guide", title: "Base64 Encoder/Decoder: Encode and decode text and files to and from Base64" },
  "developer-tools/chmod-calculator": { slug: "chmod-calculator-guide", title: "Chmod Calculator: Compute numeric and symbolic Unix file permissions" },
  "developer-tools/cron-expression-generator": { slug: "cron-expression-generator-guide", title: "Cron Expression Generator: Build and explain cron schedules with next-run preview" },
  "developer-tools/css-gradient-generator": { slug: "css-gradient-generator-guide", title: "CSS Gradient Generator: Visually build linear and radial CSS gradients with code output" },
  "developer-tools/css-minifier": { slug: "css-minifier-guide", title: "CSS Minifier: Compress CSS by stripping whitespace and comments" },
  "developer-tools/csv-to-json": { slug: "csv-to-json-guide", title: "CSV to JSON Converter: Parse CSV data into structured JSON output" },
  "developer-tools/data-file-merger": { slug: "data-file-merger-guide", title: "Data File Merger: Merge multiple JSON, CSV, TSV or XML files into one combined dataset, exportable as JSON or CSV" },
  "developer-tools/duplicate-file-finder": { slug: "duplicate-file-finder-guide", title: "Duplicate File Finder: Find exact duplicate files by content hash locally in your browser, flagging older copies as safe to delete" },
  "developer-tools/gitignore-generator": { slug: "gitignore-generator-guide", title: ".gitignore Generator: Merge multiple language, framework and OS templates into one .gitignore, with duplicate patterns removed" },
  "developer-tools/hex-to-rgb-converter": { slug: "hex-to-rgb-converter-guide", title: "Hex to RGB Converter: Convert colors between HEX, RGB and HSL formats" },
  "developer-tools/html-encoder-decoder": { slug: "html-encoder-decoder-guide", title: "HTML Encoder/Decoder: Encode and decode HTML entities in text" },
  "developer-tools/html-minifier": { slug: "html-minifier-guide", title: "HTML Minifier: Remove whitespace and comments to shrink HTML" },
  "developer-tools/javascript-minifier": { slug: "javascript-minifier-guide", title: "JavaScript Minifier: Minify JavaScript source to reduce file size" },
  "developer-tools/json-diff-checker": { slug: "json-diff-checker-guide", title: "JSON Diff Checker: Compare two JSON documents with path-level added, removed, and changed highlights" },
  "developer-tools/json-formatter": { slug: "json-formatter-guide", title: "JSON Formatter: Beautify, validate and minify JSON with syntax highlighting" },
  "developer-tools/json-to-csv": { slug: "json-to-csv-guide", title: "JSON to CSV Converter: Convert JSON arrays into downloadable CSV files" },
  "developer-tools/json-to-yaml": { slug: "json-to-yaml-guide", title: "JSON to YAML Converter: Convert between JSON and YAML formats" },
  "developer-tools/json-validator": { slug: "json-validator-guide", title: "JSON Validator: Validate JSON syntax and pinpoint errors" },
  "developer-tools/jwt-decoder": { slug: "jwt-decoder-guide", title: "JWT Decoder: Decode a JWT into its header, payload and signature" },
  "developer-tools/markdown-preview": { slug: "markdown-preview-guide", title: "Markdown Preview: Render Markdown to live HTML side by side" },
  "developer-tools/mock-data-generator": { slug: "mock-data-generator-guide", title: "Mock Data Generator: Generate fake users or products as JSON or CSV for API testing and demos" },
  "developer-tools/number-base-converter": { slug: "number-base-converter-guide", title: "Number Base Converter: Convert numbers between binary, octal, decimal and hex" },
  "developer-tools/pwa-manifest-generator": { slug: "pwa-manifest-generator-guide", title: "PWA Manifest Generator: Build manifest.json and HTML tags to turn your site into an installable Progressive Web App" },
  "developer-tools/px-to-rem-converter": { slug: "px-to-rem-converter-guide", title: "PX to REM Converter: Convert CSS pixels to rem (and back) with a customizable root font size" },
  "developer-tools/qr-code-generator": { slug: "qr-code-generator-guide", title: "QR Code Generator: Generate downloadable QR codes from text or URLs" },
  "developer-tools/regex-explainer": { slug: "regex-explainer-guide", title: "Regex Explainer: Paste a regular expression and get a plain-English, token-by-token breakdown of what it matches" },
  "developer-tools/regex-tester": { slug: "regex-tester-guide", title: "Regex Tester: Test regular expressions against sample text with live match highlighting" },
  "developer-tools/rot13-encoder-decoder": { slug: "rot13-encoder-decoder-guide", title: "ROT13 Encoder/Decoder: Apply the ROT13 letter-substitution cipher to text" },
  "developer-tools/slug-generator": { slug: "slug-generator-guide", title: "Slug Generator: Create SEO-friendly URL slugs from text" },
  "developer-tools/sql-formatter": { slug: "sql-formatter-guide", title: "SQL Formatter: Beautify and indent SQL queries for readability" },
  "developer-tools/timestamp-converter": { slug: "timestamp-converter-guide", title: "Timestamp Converter: Convert Unix epoch timestamps to and from human-readable dates" },
  "developer-tools/url-encoder-decoder": { slug: "url-encoder-decoder-guide", title: "URL Encoder/Decoder: Percent-encode and decode URLs and query parameters" },
  "developer-tools/user-agent-parser": { slug: "user-agent-parser-guide", title: "User Agent Parser: Parse a user-agent string into browser, OS and device" },
  "developer-tools/uuid-generator": { slug: "uuid-generator-guide", title: "UUID Generator: Generate v4 UUIDs singly or in bulk" },
  "developer-tools/xml-formatter": { slug: "xml-formatter-guide", title: "XML Formatter: Beautify and validate XML documents" },
  "developer-tools/yaml-to-json": { slug: "yaml-to-json-guide", title: "YAML to JSON Converter: Convert YAML to pretty-printed JSON instantly in your browser" },
  "devops-tools/backup-script-generator": { slug: "backup-script-generator-guide", title: "Backup Script Generator: Generate a cron-ready database backup script for Postgres, MySQL or MongoDB, with an optional S3 upload" },
  "devops-tools/crontab-builder": { slug: "crontab-builder-guide", title: "Crontab Builder: Build a cron expression and validate it against a real parser, with the next 5 run times previewed" },
  "devops-tools/curl-command-builder": { slug: "curl-command-builder-guide", title: "curl Command Builder: Build a curl command from a form and export the equivalent Python requests and JS fetch code" },
  "devops-tools/env-validator": { slug: "env-validator-guide", title: ".env Validator: Validate .env syntax and flag likely leaked secrets and API keys before you commit them" },
  "devops-tools/github-actions-generator": { slug: "github-actions-generator-guide", title: "GitHub Actions Generator: Generate a CI workflow YAML from ready-made Node, Python and Docker templates" },
  "devops-tools/health-check-generator": { slug: "health-check-generator-guide", title: "Health Check Config Generator: Generate a ready-to-paste health-check script and JSON config for uptime monitors from an endpoint" },
  "devops-tools/ip-address-info": { slug: "ip-address-info-guide", title: "IP Address Info & Classifier: Classify an IP as private, public, CGNAT, loopback or reserved with plain-language context and reverse-DNS" },
  "devops-tools/ip-subnet-calculator": { slug: "ip-subnet-calculator-guide", title: "IP Subnet Calculator: Calculate network, broadcast, host range and mask from a CIDR block, with a visual bit breakdown" },
  "devops-tools/kubernetes-yaml-generator": { slug: "kubernetes-yaml-generator-guide", title: "Kubernetes YAML Generator: Generate a linked Deployment, Service and Ingress in one manifest from a simple form" },
  "devops-tools/nginx-config-generator": { slug: "nginx-config-generator-guide", title: "Nginx Config Generator: Generate Nginx configs for reverse proxy, SSL termination, static sites and load balancing" },
  "devops-tools/subnet-overlap-visualizer": { slug: "subnet-overlap-visualizer-guide", title: "Subnet Overlap Visualizer: Paste multiple CIDR blocks or IP ranges and see their coverage and overlaps on a visual map" },
  "devops-tools/systemd-timer-explainer": { slug: "systemd-timer-explainer-guide", title: "Systemd Timer Explainer: Explain and build systemd OnCalendar expressions in plain English, with the next 5 run times" },
  "freelancer-tools/break-even-calculator": { slug: "break-even-calculator-guide", title: "Break-Even Calculator: Find how many projects or hours you need each month to cover fixed costs" },
  "freelancer-tools/change-order-generator": { slug: "change-order-generator-guide", title: "Scope Change Order Generator: Document out-of-scope work with added cost and time — protect yourself with a PDF change order" },
  "freelancer-tools/client-onboarding-form": { slug: "client-onboarding-form-guide", title: "Client Onboarding Form Generator: Generate a client intake questionnaire as a printable PDF or downloadable HTML form" },
  "freelancer-tools/contract-generator": { slug: "contract-generator-guide", title: "Freelance Contract Generator: Free freelance contract template & independent contractor agreement — scope, payment, IP, confidentiality, PDF" },
  "freelancer-tools/email-templates-generator": { slug: "freelance-email-templates-that-get-you-paid", title: "5 Freelance Email Templates That Actually Get You Paid (Copy & Paste)" },
  "freelancer-tools/late-fee-calculator": { slug: "late-fee-calculator-guide", title: "Late Payment Fee Calculator: Calculate late fees on overdue invoices with flat or monthly percentage rates" },
  "freelancer-tools/nda-generator": { slug: "nda-generator-guide", title: "NDA Generator: Generate a one-way or mutual non-disclosure agreement and download it as a PDF" },
  "freelancer-tools/project-estimator": { slug: "project-estimator-guide", title: "Freelance Project Estimator: Break projects into phases and tasks, add expenses and profit buffers, and get a fixed quote with timeline and " },
  "freelancer-tools/proposal-generator": { slug: "proposal-generator-guide", title: "Freelance Proposal Generator: Build a client proposal with summary, scope, timeline, pricing, and about section — export PDF" },
  "freelancer-tools/quote-calculator": { slug: "quote-calculator-guide", title: "Project Quote Calculator: Turn hours, rate, expenses, and margin into a clear project quote with cost breakdown" },
  "freelancer-tools/rate-calculator": { slug: "apr-vs-interest-rate-calculator", title: "APR Calculator — Why APR Is Higher Than the Interest Rate" },
  "freelancer-tools/self-employment-tax-calculator": { slug: "self-employment-tax-calculator-guide", title: "Self-Employment Tax Calculator: Estimate US self-employment tax or Pakistan income tax on freelance net income — for planning only" },
  "handwriting-ocr/handwriting-to-markdown": { slug: "handwriting-to-markdown-guide", title: "Handwriting to Markdown: Convert a handwritten page into clean Markdown with headings and lists" },
  "handwriting-ocr/handwriting-to-text": { slug: "handwriting-to-text-guide", title: "Handwriting to Text (OCR): Convert a photo of handwriting into digital text in any language, then optionally translate it" },
  "handwriting-ocr/handwriting-to-text-arabic": { slug: "handwriting-to-text-arabic-guide", title: "Arabic Handwriting to Text: Convert Arabic handwriting from a photo into editable Arabic text, with optional translation into another langua" },
  "handwriting-ocr/handwriting-to-text-bengali": { slug: "handwriting-to-text-bengali-guide", title: "Bengali Handwriting to Text: Convert Bengali handwriting from a photo into editable Bengali text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-chinese": { slug: "handwriting-to-text-chinese-guide", title: "Chinese Handwriting to Text: Convert Chinese handwriting from a photo into editable Chinese text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-dutch": { slug: "handwriting-to-text-dutch-guide", title: "Dutch Handwriting to Text: Convert Dutch handwriting from a photo into editable Dutch text, with optional translation into another language" },
  "handwriting-ocr/handwriting-to-text-english": { slug: "handwriting-to-text-english-guide", title: "English Handwriting to Text: Convert English handwriting from a photo into editable English text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-french": { slug: "handwriting-to-text-french-guide", title: "French Handwriting to Text: Convert French handwriting from a photo into editable French text, with optional translation into another langua" },
  "handwriting-ocr/handwriting-to-text-german": { slug: "handwriting-to-text-german-guide", title: "German Handwriting to Text: Convert German handwriting from a photo into editable German text, with optional translation into another langua" },
  "handwriting-ocr/handwriting-to-text-greek": { slug: "handwriting-to-text-greek-guide", title: "Greek Handwriting to Text: Convert Greek handwriting from a photo into editable Greek text, with optional translation into another language" },
  "handwriting-ocr/handwriting-to-text-gujarati": { slug: "handwriting-to-text-gujarati-guide", title: "Gujarati Handwriting to Text: Convert Gujarati handwriting from a photo into editable Gujarati text, with optional translation into another " },
  "handwriting-ocr/handwriting-to-text-hindi": { slug: "handwriting-to-text-hindi-guide", title: "Hindi Handwriting to Text: Convert Hindi handwriting from a photo into editable Hindi text, with optional translation into another language" },
  "handwriting-ocr/handwriting-to-text-indonesian": { slug: "handwriting-to-text-indonesian-guide", title: "Indonesian Handwriting to Text: Convert Indonesian handwriting from a photo into editable Indonesian text, with optional translation into an" },
  "handwriting-ocr/handwriting-to-text-italian": { slug: "handwriting-to-text-italian-guide", title: "Italian Handwriting to Text: Convert Italian handwriting from a photo into editable Italian text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-japanese": { slug: "handwriting-to-text-japanese-guide", title: "Japanese Handwriting to Text: Convert Japanese handwriting from a photo into editable Japanese text, with optional translation into another " },
  "handwriting-ocr/handwriting-to-text-kannada": { slug: "handwriting-to-text-kannada-guide", title: "Kannada Handwriting to Text: Convert Kannada handwriting from a photo into editable Kannada text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-korean": { slug: "handwriting-to-text-korean-guide", title: "Korean Handwriting to Text: Convert Korean handwriting from a photo into editable Korean text, with optional translation into another langua" },
  "handwriting-ocr/handwriting-to-text-malayalam": { slug: "handwriting-to-text-malayalam-guide", title: "Malayalam Handwriting to Text: Convert Malayalam handwriting from a photo into editable Malayalam text, with optional translation into anoth" },
  "handwriting-ocr/handwriting-to-text-marathi": { slug: "handwriting-to-text-marathi-guide", title: "Marathi Handwriting to Text: Convert Marathi handwriting from a photo into editable Marathi text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-persian": { slug: "handwriting-to-text-persian-guide", title: "Persian Handwriting to Text: Convert Persian handwriting from a photo into editable Persian text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-polish": { slug: "handwriting-to-text-polish-guide", title: "Polish Handwriting to Text: Convert Polish handwriting from a photo into editable Polish text, with optional translation into another langua" },
  "handwriting-ocr/handwriting-to-text-portuguese": { slug: "handwriting-to-text-portuguese-guide", title: "Portuguese Handwriting to Text: Convert Portuguese handwriting from a photo into editable Portuguese text, with optional translation into an" },
  "handwriting-ocr/handwriting-to-text-punjabi": { slug: "handwriting-to-text-punjabi-guide", title: "Punjabi Handwriting to Text: Convert Punjabi handwriting from a photo into editable Punjabi text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-russian": { slug: "handwriting-to-text-russian-guide", title: "Russian Handwriting to Text: Convert Russian handwriting from a photo into editable Russian text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-spanish": { slug: "handwriting-to-text-spanish-guide", title: "Spanish Handwriting to Text: Convert Spanish handwriting from a photo into editable Spanish text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-swedish": { slug: "handwriting-to-text-swedish-guide", title: "Swedish Handwriting to Text: Convert Swedish handwriting from a photo into editable Swedish text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-tamil": { slug: "handwriting-to-text-tamil-guide", title: "Tamil Handwriting to Text: Convert Tamil handwriting from a photo into editable Tamil text, with optional translation into another language" },
  "handwriting-ocr/handwriting-to-text-telugu": { slug: "handwriting-to-text-telugu-guide", title: "Telugu Handwriting to Text: Convert Telugu handwriting from a photo into editable Telugu text, with optional translation into another langua" },
  "handwriting-ocr/handwriting-to-text-thai": { slug: "handwriting-to-text-thai-guide", title: "Thai Handwriting to Text: Convert Thai handwriting from a photo into editable Thai text, with optional translation into another language" },
  "handwriting-ocr/handwriting-to-text-turkish": { slug: "handwriting-to-text-turkish-guide", title: "Turkish Handwriting to Text: Convert Turkish handwriting from a photo into editable Turkish text, with optional translation into another lan" },
  "handwriting-ocr/handwriting-to-text-ukrainian": { slug: "handwriting-to-text-ukrainian-guide", title: "Ukrainian Handwriting to Text: Convert Ukrainian handwriting from a photo into editable Ukrainian text, with optional translation into anoth" },
  "handwriting-ocr/handwriting-to-text-vietnamese": { slug: "handwriting-to-text-vietnamese-guide", title: "Vietnamese Handwriting to Text: Convert Vietnamese handwriting from a photo into editable Vietnamese text, with optional translation into an" },
  "handwriting-ocr/handwritten-form-extractor": { slug: "handwritten-form-extractor-guide", title: "Handwritten Form Extractor: Pull filled fields from a handwritten form into JSON, CSV, or a Markdown table" },
  "handwriting-ocr/handwritten-math-ocr": { slug: "handwritten-math-to-latex-guide", title: "How to Convert Handwritten Math to LaTeX From a Photo" },
  "handwriting-ocr/handwritten-notes-summarizer": { slug: "handwritten-notes-summarizer-guide", title: "Turn Handwritten Notes Into Summaries and Study Flashcards" },
  "handwriting-ocr/handwritten-table-ocr": { slug: "handwritten-table-ocr-guide", title: "Handwritten Table OCR: Turn a photo of a handwritten table or grid into Markdown, CSV, or JSON rows" },
  "health-tools/bac-calculator": { slug: "bac-calculator-guide", title: "Blood Alcohol (BAC) Calculator: Estimate blood alcohol concentration with the Widmark formula and a time-to-sober estimate" },
  "health-tools/body-surface-area-calculator": { slug: "body-surface-area-calculator-guide", title: "Body Surface Area Calculator: Compute body surface area with the Mosteller and Du Bois formulas side by side" },
  "health-tools/calories-burned-calculator": { slug: "calories-burned-calculator-guide", title: "Calories Burned Calculator: Estimate calories burned for dozens of activities using MET values, your weight and duration" },
  "health-tools/heart-rate-zone-calculator": { slug: "heart-rate-zone-calculator-guide", title: "Heart Rate Zone Calculator: Calculate your 5 training heart-rate zones using the Karvonen method with your resting heart rate" },
  "health-tools/macro-calculator": { slug: "macro-calculator-guide", title: "Macro Calculator: Split your daily calories into protein, carbs and fat with diet-style presets and a per-meal breakdown" },
  "health-tools/one-rep-max-calculator": { slug: "one-rep-max-calculator-guide", title: "One Rep Max Calculator: Estimate your 1RM from a lift and reps, with a full percentage-of-max training table" },
  "health-tools/pace-calculator": { slug: "pace-calculator-guide", title: "Running Pace Calculator: Turn a distance and time into pace per km and per mile, plus projected 5K, 10K, half and marathon times" },
  "health-tools/protein-intake-calculator": { slug: "protein-intake-calculator-guide", title: "Protein Intake Calculator: Find your daily protein target range based on body weight and your goal" },
  "health-tools/waist-to-hip-ratio-calculator": { slug: "waist-to-hip-ratio-calculator-guide", title: "Waist-to-Hip Ratio Calculator: Calculate your waist-to-hip ratio and see your health-risk category by sex" },
  "health-tools/water-intake-calculator": { slug: "water-intake-calculator-guide", title: "Water Intake Calculator: Estimate your daily water needs based on weight, exercise and climate, shown in litres, cups and bottles" },
  "home-trade-calculators/3d-print-cost-calculator": { slug: "3d-print-cost-calculator-guide", title: "3D Print Cost Calculator: Estimate 3D print cost from filament grams, spool price, print hours, printer watts, and electricity rate" },
  "home-trade-calculators/absorption-rate-calculator": { slug: "absorption-rate-calculator-guide", title: "Absorption Rate Calculator: Calculate real estate absorption rate and months of housing supply from sales and active listings" },
  "home-trade-calculators/ac-tonnage-calculator": { slug: "ac-tonnage-calculator-guide", title: "AC Tonnage Calculator: Convert home square footage, insulation, and climate into cooling tons and BTU, rounded to the next half ton" },
  "home-trade-calculators/air-changes-calculator": { slug: "air-changes-calculator-guide", title: "Air Changes Calculator: Find air changes per hour from room cubic feet and fan CFM, plus minutes for one full air change" },
  "home-trade-calculators/aquarium-calculator": { slug: "aquarium-calculator-guide", title: "Aquarium Calculator: Convert tank dimensions to gallons and liters, plus heater watts, water-change volume, and salt dose" },
  "home-trade-calculators/btu-calculator": { slug: "btu-calculator-guide", title: "BTU Calculator: Estimate room cooling BTU from size, ceiling height, sun, people, windows, and a kitchen load, plus AC tons" },
  "home-trade-calculators/budget-calculator": { slug: "budget-calculator-guide", title: "Budget Calculator: Split monthly income across housing, food, transport, and debt, then see what is left and the savings rate" },
  "home-trade-calculators/business-valuation-calculator": { slug: "business-valuation-calculator-guide", title: "Business Valuation Calculator: Estimate a small-business value from seller earnings and revenue using multiples you choose" },
  "home-trade-calculators/car-trade-equity-calculator": { slug: "car-trade-equity-calculator-guide", title: "Car Trade-In Equity Calculator: Find trade-in equity, taxable price after a trade, and sales tax compared with no trade-in" },
  "home-trade-calculators/cat-age-calculator": { slug: "cat-age-calculator-guide", title: "Cat Age Calculator: Convert cat years and months into an approximate human-equivalent age" },
  "home-trade-calculators/cfm-calculator": { slug: "cfm-calculator-guide", title: "CFM Calculator: Calculate airflow CFM from room volume and air changes per hour for a fan, hood, or workshop" },
  "home-trade-calculators/closing-cost-calculator": { slug: "closing-cost-calculator-guide", title: "Closing Cost Calculator: Estimate buyer closing costs from lender fees, title, inspection, appraisal, and prepaid tax and insurance" },
  "home-trade-calculators/coffee-ratio-calculator": { slug: "coffee-ratio-calculator-guide", title: "Coffee Ratio Calculator: Calculate pour-over, French press, drip, cold brew, and espresso water from a coffee dose and brew ratio" },
  "home-trade-calculators/compost-calculator": { slug: "compost-calculator-guide", title: "Compost Calculator: Balance browns and greens by volume and see how much to add for a target compost ratio" },
  "home-trade-calculators/deck-calculator": { slug: "deck-calculator-guide", title: "Deck Calculator: Estimate deck boards, joists, and square footage from deck size, board width, gap, and joist spacing" },
  "home-trade-calculators/down-payment-calculator": { slug: "down-payment-calculator-guide", title: "Down Payment Calculator: Compare 3%, 5%, 10%, 20%, and a custom down payment, with loan amount and whether PMI is likely" },
  "home-trade-calculators/electricity-cost-calculator": { slug: "electricity-cost-calculator-guide", title: "Electricity Cost Calculator: Estimate appliance electricity cost from watts, hours per day, and your price per kWh" },
  "home-trade-calculators/employee-cost-calculator": { slug: "employee-cost-calculator-guide", title: "Employee Cost Calculator: Estimate fully loaded employee cost from salary, benefits percent, and employer payroll tax" },
  "home-trade-calculators/ev-charging-cost-calculator": { slug: "ev-charging-cost-calculator-guide", title: "EV Charging Cost Calculator: Calculate electric vehicle charging cost, kWh, and hours from miles, efficiency, and charger kW" },
  "home-trade-calculators/fuel-mix-calculator": { slug: "fuel-mix-calculator-guide", title: "Fuel Mix Calculator: Calculate 2-stroke oil for a 50:1, 40:1, 32:1, or 25:1 gas mix in ounces and milliliters" },
  "home-trade-calculators/hexagon-quilt-calculator": { slug: "hexagon-quilt-calculator-guide", title: "Hexagon Quilt Calculator: Estimate fabric area for hexagon quilt pieces from side length, seam allowance, and how many hexes you need" },
  "home-trade-calculators/hull-speed-calculator": { slug: "hull-speed-calculator-guide", title: "Hull Speed Calculator: Calculate displacement hull speed in knots, mph, and km/h from waterline length" },
  "home-trade-calculators/kerf-calculator": { slug: "kerf-calculator-guide", title: "Kerf Calculator: See how many pieces a board yields after saw kerf, and how many boards to buy" },
  "home-trade-calculators/kw-to-kva-calculator": { slug: "kw-to-kva-calculator-guide", title: "kW to kVA Calculator: Convert kilowatts to kVA with power factor, and estimate single-phase or three-phase amps" },
  "home-trade-calculators/loan-comparison-calculator": { slug: "loan-comparison-calculator-guide", title: "Loan Comparison Calculator: Compare two loans side by side on monthly payment, total interest, and total amount paid" },
  "home-trade-calculators/lumber-calculator": { slug: "lumber-calculator-guide", title: "Lumber Calculator: Calculate board feet, linear feet, and lumber cost from thickness, width, length, and board count" },
  "home-trade-calculators/marketplace-fee-calculator": { slug: "marketplace-fee-calculator-guide", title: "Marketplace Fee Calculator: Calculate seller fees, shipping, product cost, net profit, and margin for an online marketplace listing" },
  "home-trade-calculators/miter-angle-calculator": { slug: "miter-angle-calculator-guide", title: "Miter Angle Calculator: Find the miter saw angle and interior corner for a square, hexagon, octagon, or any equal-sided frame" },
  "home-trade-calculators/molarity-calculator": { slug: "molarity-calculator-guide", title: "Molarity Calculator: Calculate solution molarity from grams and molar mass, or the grams to weigh for a target molarity" },
  "home-trade-calculators/ohms-law-calculator": { slug: "ohms-law-calculator-guide", title: "Ohm's Law Calculator: Solve voltage, current, resistance, and watts with Ohm's law from any two electrical values" },
  "home-trade-calculators/plant-spacing-calculator": { slug: "plant-spacing-calculator-guide", title: "Plant Spacing Calculator: Count how many plants fit in a garden bed with square or triangular spacing" },
  "home-trade-calculators/refinance-calculator": { slug: "refinance-calculator-guide", title: "Refinance Calculator: Compare your current mortgage payment with a refinance, including break-even months and total interest" },
  "home-trade-calculators/rental-property-calculator": { slug: "rental-property-calculator-guide", title: "Rental Property Calculator: Estimate cap rate, monthly cash flow, cash-on-cash return, and mortgage payment for a rental property" },
  "home-trade-calculators/retirement-calculator": { slug: "retirement-calculator-guide", title: "Retirement Calculator: Project retirement savings from a current balance, monthly contribution, return, and years" },
  "home-trade-calculators/seller-net-calculator": { slug: "seller-net-calculator-guide", title: "Seller Net Calculator: Estimate seller net proceeds after commission, mortgage payoff, closing costs, and repairs" },
  "home-trade-calculators/spray-foam-calculator": { slug: "spray-foam-calculator-guide", title: "Spray Foam Calculator: Convert wall area and foam thickness into board feet, spray foam kits, and material cost" },
  "home-trade-calculators/tithing-calculator": { slug: "tithing-calculator-guide", title: "Tithing Calculator: Calculate a tithe or any percent of weekly, monthly, or yearly income" },
  "home-trade-calculators/vehicle-depreciation-calculator": { slug: "vehicle-depreciation-calculator-guide", title: "Vehicle Depreciation Calculator: Project car value year by year with a declining-balance depreciation rate" },
  "home-trade-calculators/voltage-drop-calculator": { slug: "voltage-drop-calculator-guide", title: "Voltage Drop Calculator: Calculate voltage drop and percent drop for copper or aluminum wire by AWG, amps, distance, and phase" },
  "home-trade-calculators/wire-size-calculator": { slug: "wire-size-calculator-guide", title: "Wire Size Calculator: Pick a wire gauge from load amps, run length, voltage, and a maximum voltage-drop percent" },
  "image-tools/add-watermark-to-image": { slug: "add-watermark-to-image-guide", title: "Add Watermark to Image: Overlay text or logo watermarks onto images" },
  "image-tools/aspect-ratio-calculator": { slug: "aspect-ratio-for-social", title: "Aspect Ratios for YouTube, Reels & Instagram (Quick Guide)" },
  "image-tools/avif-to-jpg": { slug: "avif-to-jpg-guide", title: "AVIF to JPG: Convert modern AVIF images to widely supported JPG" },
  "image-tools/avif-to-webp": { slug: "avif-to-webp-guide", title: "AVIF to WebP: Convert AVIF images to efficient WebP format" },
  "image-tools/base64-to-image": { slug: "base64-to-image-guide", title: "Base64 to Image: Decode a Base64 string back into a downloadable image" },
  "image-tools/blur-image": { slug: "blur-image-guide", title: "Blur Image: Apply adjustable blur to all or part of an image" },
  "image-tools/bmp-to-jpg": { slug: "bmp-to-jpg-guide", title: "BMP to JPG: Convert BMP bitmap images to compressed JPG files" },
  "image-tools/bmp-to-pdf": { slug: "bmp-to-pdf-guide", title: "BMP to PDF: Merge BMP images into a single PDF document" },
  "image-tools/circle-crop-image": { slug: "circle-crop-image-guide", title: "Circle Crop Image: Crop an image into a transparent circle" },
  "image-tools/collage-maker": { slug: "collage-maker-guide", title: "Collage Maker: Combine multiple photos into a grid collage" },
  "image-tools/color-extractor-from-image": { slug: "color-extractor-from-image-guide", title: "Color Extractor from Image: Extract a dominant color palette from a photo" },
  "image-tools/combine-images": { slug: "combine-images-guide", title: "Combine Images: Stitch images together horizontally or vertically" },
  "image-tools/compress-image": { slug: "midjourney-vs-dalle", title: "Midjourney vs DALL·E — Which AI Image Generator Should You Use?" },
  "image-tools/crop-image": { slug: "crop-image-guide", title: "Crop Image: Crop images freely or to fixed aspect ratios" },
  "image-tools/duplicate-photo-finder": { slug: "duplicate-photo-finder-online-free-storage", title: "Duplicate Photo Finder Online — Remove Similar Photos and Free Up Storage" },
  "image-tools/favicon-generator": { slug: "favicon-generator-guide", title: "Favicon Generator: Create multi-size favicons and ICO files from an image" },
  "image-tools/flip-image": { slug: "flip-image-guide", title: "Flip Image: Mirror an image horizontally or vertically" },
  "image-tools/gif-maker": { slug: "gif-maker-guide", title: "GIF Maker: Create animated GIFs from multiple images in your browser" },
  "image-tools/gif-optimizer": { slug: "gif-optimizer-guide", title: "GIF Optimizer: Compress and optimize GIF file size in your browser" },
  "image-tools/gif-resizer": { slug: "gif-resizer-guide", title: "GIF Resizer: Resize animated GIFs with presets or custom dimensions" },
  "image-tools/gif-rotator": { slug: "gif-rotator-guide", title: "GIF Rotator: Rotate or flip animated GIFs on every frame" },
  "image-tools/gif-to-jpg": { slug: "gif-to-jpg-guide", title: "GIF to JPG: Extract all GIF frames as JPG images in a ZIP" },
  "image-tools/gif-to-png": { slug: "gif-to-png-guide", title: "GIF to PNG: Extract all GIF frames as PNG images in a ZIP" },
  "image-tools/gif-to-video": { slug: "gif-to-video-guide", title: "GIF to Video: Convert animated GIFs to WebM video" },
  "image-tools/gif-to-webp": { slug: "gif-to-webp-guide", title: "GIF to WebP: Convert GIF animation frames to WebP images" },
  "image-tools/gif-trimmer": { slug: "gif-trimmer-guide", title: "GIF Trimmer: Trim GIF animations to a specific frame range" },
  "image-tools/grayscale-image": { slug: "grayscale-image-guide", title: "Grayscale Image: Convert a color image to black and white" },
  "image-tools/heic-to-jpg": { slug: "heic-to-jpg-guide", title: "HEIC to JPG: Convert iPhone HEIC photos to JPG images" },
  "image-tools/home-color-visualizer": { slug: "home-color-visualizer-guide", title: "Home Color Visualizer: Upload a photo of your home or room, try wall/door/furniture colors, and preview what looks best" },
  "image-tools/image-color-picker": { slug: "image-color-picker-guide", title: "Image Color Picker: Pick HEX/RGB colors from any pixel of an image" },
  "image-tools/image-to-base64": { slug: "image-to-base64-guide", title: "Image to Base64: Encode an image into a Base64 data URI string" },
  "image-tools/image-to-ico": { slug: "image-to-ico-guide", title: "Image to ICO: Convert PNG/JPG images into Windows ICO icons" },
  "image-tools/image-to-pdf": { slug: "image-to-pdf-guide", title: "Image to PDF: Convert images into a single downloadable PDF" },
  "image-tools/jfif-to-jpg": { slug: "jfif-to-jpg-guide", title: "JFIF to JPG: Convert JFIF images to standard JPG format in your browser" },
  "image-tools/jfif-to-png": { slug: "jfif-to-png-guide", title: "JFIF to PNG: Convert JFIF images to lossless PNG format" },
  "image-tools/jpg-to-png": { slug: "jpg-to-png-guide", title: "JPG to PNG: Convert JPG images to lossless PNG format" },
  "image-tools/jpg-to-webp": { slug: "jpg-to-webp-guide", title: "JPG to WebP: Convert JPG images to modern WebP format" },
  "image-tools/meme-generator": { slug: "meme-generator-guide", title: "Meme Generator: Add top and bottom text captions to an image" },
  "image-tools/passport-photo-maker": { slug: "passport-photo-maker-guide", title: "Passport Photo Maker: Crop and size photos to passport/visa requirements" },
  "image-tools/pixelate-image": { slug: "pixelate-image-guide", title: "Pixelate Image: Pixelate or censor regions of an image" },
  "image-tools/png-to-jpg": { slug: "png-to-jpg-guide", title: "PNG to JPG: Convert PNG images to compressed JPG files" },
  "image-tools/png-to-svg": { slug: "png-to-svg-guide", title: "PNG to SVG: Trace a raster PNG into a scalable SVG vector" },
  "image-tools/png-to-webp": { slug: "png-to-webp-guide", title: "PNG to WebP: Convert PNG images to smaller WebP files" },
  "image-tools/resize-image": { slug: "resize-image-guide", title: "Resize Image: Change image dimensions by pixels or percentage" },
  "image-tools/rotate-image": { slug: "rotate-image-guide", title: "Rotate Image: Rotate an image by 90 degrees or any angle" },
  "image-tools/screenshot-auto-anonymizer": { slug: "screenshot-auto-anonymizer-guide", title: "Screenshot Auto-Anonymizer: Blur or blackout faces, text, credit cards, and sensitive objects in screenshots — 100% private in your browser" },
  "image-tools/svg-to-png": { slug: "svg-to-png-guide", title: "SVG to PNG: Rasterize SVG vector files to PNG at any size" },
  "image-tools/webp-to-jpg": { slug: "webp-to-jpg-guide", title: "WebP to JPG: Convert WebP images to widely supported JPG" },
  "image-tools/webp-to-png": { slug: "webp-to-png-guide", title: "WebP to PNG: Convert WebP images to lossless PNG format" },
  "pdf-tools/add-page-numbers-to-pdf": { slug: "add-page-numbers-to-pdf-guide", title: "Add Page Numbers to PDF: Insert customizable page numbers into a PDF" },
  "pdf-tools/add-watermark-to-pdf": { slug: "add-watermark-to-pdf-guide", title: "Add Watermark to PDF: Stamp text or image watermarks across PDF pages" },
  "pdf-tools/bank-statement-to-excel": { slug: "bank-statement-to-excel-guide", title: "Bank Statement to Excel: Extract bank statement PDF data to CSV for Excel" },
  "pdf-tools/cbz-to-pdf": { slug: "cbz-to-pdf-guide", title: "CBZ to PDF: Convert CBZ comic archives to a single PDF" },
  "pdf-tools/compress-pdf": { slug: "compress-pdf-guide", title: "Compress PDF: Reduce PDF file size while preserving readable quality" },
  "pdf-tools/crop-pdf": { slug: "crop-pdf-guide", title: "Crop PDF: Trim margins and crop the visible area of PDF pages" },
  "pdf-tools/csv-to-pdf": { slug: "csv-to-pdf-guide", title: "CSV to PDF: Turn CSV spreadsheet data into a readable PDF" },
  "pdf-tools/delete-pdf-pages": { slug: "delete-pdf-pages-guide", title: "Delete PDF Pages: Remove selected pages from a PDF document" },
  "pdf-tools/duplicate-pdf-pages": { slug: "duplicate-pdf-pages-guide", title: "Duplicate PDF Pages: Copy and repeat selected pages within a PDF" },
  "pdf-tools/edit-pdf": { slug: "edit-pdf-guide", title: "Edit PDF: Add text, images, shapes, and annotations to a PDF" },
  "pdf-tools/epub-to-pdf": { slug: "epub-to-pdf-guide", title: "EPUB to PDF: Convert EPUB ebooks to PDF for printing or sharing" },
  "pdf-tools/excel-to-pdf": { slug: "excel-to-pdf-guide", title: "Excel to PDF: Convert CSV exports from Excel into PDF files" },
  "pdf-tools/extract-images-from-pdf": { slug: "extract-images-from-pdf-guide", title: "Extract Images from PDF: Pull all embedded images out of a PDF file" },
  "pdf-tools/extract-pdf-pages": { slug: "extract-pdf-pages-guide", title: "Extract PDF Pages: Pull selected pages out into a new PDF file" },
  "pdf-tools/extract-text-from-pdf": { slug: "extract-text-from-pdf-guide", title: "Extract Text from PDF: Copy all selectable text out of a PDF as plain text" },
  "pdf-tools/fill-pdf-form": { slug: "fill-pdf-form-guide", title: "Fill PDF Form: Fill in and flatten interactive PDF form fields" },
  "pdf-tools/flatten-pdf": { slug: "flatten-pdf-guide", title: "Flatten PDF: Merge annotations and form fields into static content" },
  "pdf-tools/images-to-pdf": { slug: "images-to-pdf-guide", title: "Images to PDF: Batch combine multiple images into one ordered PDF" },
  "pdf-tools/jpg-to-pdf": { slug: "jpg-to-pdf-guide", title: "JPG to PDF: Convert JPG and other images into a single PDF" },
  "pdf-tools/merge-pdf": { slug: "merge-pdf-guide", title: "Merge PDF: Combine multiple PDF files into one document in any order" },
  "pdf-tools/organize-pdf": { slug: "organize-pdf-guide", title: "Organize PDF: Reorder, rearrange, and sort PDF pages by drag and drop" },
  "pdf-tools/pdf-page-counter": { slug: "pdf-page-counter-guide", title: "PDF Page Counter: Instantly count the number of pages in a PDF" },
  "pdf-tools/pdf-to-cbz": { slug: "pdf-to-cbz-guide", title: "PDF to CBZ: Convert PDF pages into a CBZ comic archive" },
  "pdf-tools/pdf-to-excel": { slug: "pdf-to-excel-guide", title: "PDF to Excel: Extract PDF table data and download as CSV for Excel" },
  "pdf-tools/pdf-to-jpg": { slug: "pdf-to-jpg-guide", title: "PDF to JPG: Convert each PDF page into a downloadable JPG image" },
  "pdf-tools/pdf-to-pdf-a": { slug: "pdf-to-pdf-a-guide", title: "PDF to PDF/A: Prepare PDFs for long-term archival (PDF/A style export)" },
  "pdf-tools/pdf-to-png": { slug: "pdf-to-png-guide", title: "PDF to PNG: Render PDF pages as high-quality PNG images" },
  "pdf-tools/pdf-to-word": { slug: "pdf-to-word-guide", title: "PDF to Word: Convert a PDF into an editable DOC/DOCX document" },
  "pdf-tools/png-to-pdf": { slug: "png-to-pdf-guide", title: "PNG to PDF: Turn one or more PNG images into a PDF document" },
  "pdf-tools/protect-pdf": { slug: "protect-pdf-guide", title: "Protect PDF: Add a password and encryption to lock a PDF" },
  "pdf-tools/resize-pdf": { slug: "resize-pdf-guide", title: "Resize PDF: Scale PDF pages to A4, Letter, or custom dimensions" },
  "pdf-tools/reverse-pdf-pages": { slug: "reverse-pdf-pages-guide", title: "Reverse PDF Pages: Flip the page order of a PDF document" },
  "pdf-tools/rotate-pdf": { slug: "rotate-pdf-guide", title: "Rotate PDF: Rotate one or all pages of a PDF and save permanently" },
  "pdf-tools/sign-pdf": { slug: "sign-pdf-guide", title: "Sign PDF: Preview PDF pages, draw/type/upload signatures, drag & resize placement, multi-page signing — free in browser" },
  "pdf-tools/split-pdf": { slug: "split-pdf-guide", title: "Split PDF: Separate a PDF into multiple files by page ranges" },
  "pdf-tools/split-pdf-in-half": { slug: "split-pdf-in-half-guide", title: "Split PDF in Half: Cut each PDF page vertically or horizontally into two" },
  "pdf-tools/txt-to-pdf": { slug: "txt-to-pdf-guide", title: "TXT to PDF: Convert plain text files into a formatted PDF document" },
  "pdf-tools/unlock-pdf": { slug: "unlock-pdf-guide", title: "Unlock PDF: Remove a known password from a PDF file" },
  "pdf-tools/word-to-pdf": { slug: "word-to-pdf-guide", title: "Word to PDF: Convert DOC/DOCX documents into PDF files" },
  "security-password-tools/aes-encrypt-decrypt": { slug: "aes-encrypt-decrypt-guide", title: "AES Text Encrypt/Decrypt: Encrypt and decrypt text with AES-GCM and a passphrase, fully client-side" },
  "security-password-tools/api-key-generator": { slug: "api-key-generator-guide", title: "API Key Generator: Generate random API keys and secret tokens" },
  "security-password-tools/argon2-hash-generator": { slug: "argon2-hash-generator-guide", title: "Argon2 Hash Generator: Hash passwords with Argon2id, with tunable parameters" },
  "security-password-tools/base64-hash-generator": { slug: "base64-hash-generator-guide", title: "Base64 Hash Generator: Hash input and output the digest in Base64 form" },
  "security-password-tools/bcrypt-generator": { slug: "bcrypt-generator-guide", title: "Bcrypt Generator: Hash passwords with bcrypt and verify them, with adjustable rounds" },
  "security-password-tools/bulk-password-generator": { slug: "bulk-password-generator-guide", title: "Bulk Password Generator: Generate many strong passwords at once for export" },
  "security-password-tools/caesar-cipher": { slug: "caesar-cipher-guide", title: "Caesar Cipher Tool: Encrypt and decrypt text using a shift-based Caesar cipher" },
  "security-password-tools/crc32-generator": { slug: "crc32-generator-guide", title: "CRC32 Checksum Generator: Compute CRC32 checksums for text or data" },
  "security-password-tools/csrf-token-generator": { slug: "csrf-token-generator-guide", title: "CSRF Token Generator: Generate random anti-CSRF tokens for forms" },
  "security-password-tools/encryption-key-generator": { slug: "encryption-key-generator-guide", title: "Encryption Key Generator: Generate random AES keys in 128/192/256-bit lengths" },
  "security-password-tools/hash-identifier": { slug: "hash-identifier-guide", title: "Hash Identifier: Detect the likely hash algorithm from a given hash string" },
  "security-password-tools/hmac-generator": { slug: "hmac-generator-guide", title: "HMAC Generator: Compute HMAC signatures with a chosen hash and secret key" },
  "security-password-tools/htpasswd-generator": { slug: "htpasswd-generator-guide", title: "htpasswd Generator: Create Apache/Nginx htpasswd entries with bcrypt or APR1" },
  "security-password-tools/jwt-verifier": { slug: "jwt-verifier-guide", title: "JWT Signature Verifier: Verify a JWT signature against a provided secret or key" },
  "security-password-tools/md5-hash-generator": { slug: "md5-hash-generator-guide", title: "MD5 Hash Generator: Compute the MD5 hash of any input text" },
  "security-password-tools/ntlm-hash-generator": { slug: "ntlm-hash-generator-guide", title: "NTLM Hash Generator: Compute NTLM hashes from password input" },
  "security-password-tools/passphrase-generator": { slug: "passphrase-generator-guide", title: "Passphrase Generator: Build memorable Diceware-style word passphrases" },
  "security-password-tools/password-entropy-calculator": { slug: "password-entropy-calculator-guide", title: "Password Entropy Calculator: Calculate the bits of entropy in a password" },
  "security-password-tools/password-generator": { slug: "password-generator-guide", title: "Password Generator: Generate strong random passwords with adjustable length and character sets" },
  "security-password-tools/password-strength-checker": { slug: "password-strength-checker-guide", title: "Password Strength Checker: Estimate password strength and crack time in the browser" },
  "security-password-tools/pin-generator": { slug: "pin-generator-guide", title: "PIN Generator: Generate random numeric PIN codes of chosen length" },
  "security-password-tools/random-token-generator": { slug: "random-token-generator-guide", title: "Random Token Generator: Produce secure random tokens of configurable length and charset" },
  "security-password-tools/rot47-encoder-decoder": { slug: "rot47-encoder-decoder-guide", title: "ROT47 Encoder/Decoder: Apply the ROT47 substitution cipher to text" },
  "security-password-tools/salt-generator": { slug: "salt-generator-guide", title: "Salt Generator: Generate random cryptographic salts in hex or Base64" },
  "security-password-tools/secure-uuid-generator": { slug: "secure-uuid-generator-guide", title: "Secure UUID Generator: Generate cryptographically secure v4 UUIDs" },
  "security-password-tools/sha1-hash-generator": { slug: "sha1-hash-generator-guide", title: "SHA-1 Hash Generator: Compute SHA-1 hashes for text input" },
  "security-password-tools/sha256-hash-generator": { slug: "sha256-hash-generator-guide", title: "SHA-256 Hash Generator: Generate SHA-256 hashes via the Web Crypto API" },
  "security-password-tools/sha512-hash-generator": { slug: "sha512-hash-generator-guide", title: "SHA-512 Hash Generator: Generate SHA-512 hashes for text" },
  "security-password-tools/totp-generator": { slug: "totp-generator-guide", title: "TOTP / 2FA Code Generator: Generate time-based OTP codes from a secret for 2FA testing" },
  "security-password-tools/wifi-qr-code-generator": { slug: "wifi-qr-code-generator-guide", title: "WiFi QR Code Generator: Create a QR code that shares WiFi credentials for easy connection" },
  "seo-web-tools/ads-txt-generator": { slug: "ads-txt-generator-guide", title: "ads.txt Generator: Create a valid ads.txt file for Google AdSense and ad networks" },
  "seo-web-tools/ai-meta-tag-writer": { slug: "ai-meta-tag-writer-guide", title: "AI Meta Tag Writer: AI-written title tags and meta descriptions optimized for CTR and character limits" },
  "seo-web-tools/ai-seo-outline-generator": { slug: "ai-seo-outline-generator-guide", title: "AI SEO Outline Generator: AI article outline with H2/H3 structure tuned for featured snippets and search intent" },
  "seo-web-tools/ai-seo-page-audit": { slug: "ai-seo-page-audit-guide", title: "AI SEO Page Audit: AI technical and on-page SEO audit from pasted HTML or page text with prioritized fixes" },
  "seo-web-tools/backlink-profile-analyzer": { slug: "backlink-profile-analyzer-guide", title: "Backlink Profile Analyzer: Analyze Ahrefs/Semrush/Moz backlink CSV exports for anchors, referring hosts, and follow mix" },
  "seo-web-tools/breadcrumb-schema-generator": { slug: "breadcrumb-schema-generator-guide", title: "Breadcrumb Schema Generator: Create BreadcrumbList structured data from a page path" },
  "seo-web-tools/canonical-tag-generator": { slug: "canonical-tag-generator-guide", title: "Canonical Tag Generator: Create rel=canonical link tags to prevent duplicate content" },
  "seo-web-tools/code-to-text-ratio-checker": { slug: "code-to-text-ratio-checker-guide", title: "Code to Text Ratio Checker: Calculate the ratio of visible text to HTML code from pasted markup" },
  "seo-web-tools/content-brief-generator": { slug: "content-brief-generator-guide", title: "Content Brief Generator: AI SEO content brief with outline, PAA questions, keywords, and on-page checklist" },
  "seo-web-tools/disavow-file-generator": { slug: "disavow-file-generator-guide", title: "Disavow File Generator: Build a Google Search Console disavow.txt from spam domains and URLs" },
  "seo-web-tools/domain-name-finder": { slug: "domain-name-finder-guide", title: "Domain Name Finder: Suggest available domain names from your project description — only shows domains that look free to register" },
  "seo-web-tools/email-extractor": { slug: "email-extractor-guide", title: "Email Extractor: Extract or scan pasted text/HTML for exposed email addresses" },
  "seo-web-tools/faq-schema-generator": { slug: "faq-schema-generator-guide", title: "FAQ Schema Generator: Generate FAQPage JSON-LD from question/answer pairs" },
  "seo-web-tools/heading-structure-analyzer": { slug: "heading-structure-analyzer-guide", title: "Heading Structure Analyzer: Audit H1–H6 outlines in page HTML for multiple H1s, skipped levels, and empty headings" },
  "seo-web-tools/howto-schema-generator": { slug: "howto-schema-generator-guide", title: "HowTo Schema Generator: Generate HowTo JSON-LD structured data from a title and step-by-step list" },
  "seo-web-tools/hreflang-tag-generator": { slug: "hreflang-tag-generator-guide", title: "Hreflang Tag Generator: Generate hreflang tags for multilingual and regional targeting" },
  "seo-web-tools/htaccess-generator": { slug: "htaccess-generator-guide", title: ".htaccess Generator: Generate .htaccess rules for redirects, caching, and security" },
  "seo-web-tools/html-tag-stripper": { slug: "html-tag-stripper-guide", title: "HTML Tag Stripper: Remove HTML tags to extract plain text from markup" },
  "seo-web-tools/indexing-readiness-checker": { slug: "indexing-readiness-checker-guide", title: "Indexing Readiness Checker: Audit a live URL for noindex, robots.txt blocks, canonical issues, and other indexability problems" },
  "seo-web-tools/indexnow-url-submitter": { slug: "indexnow-url-submitter-guide", title: "IndexNow URL Submitter: Generate an IndexNow key and notify Bing, Yandex, and other engines when your URLs change" },
  "seo-web-tools/internal-link-suggester": { slug: "internal-link-suggester-guide", title: "Internal Link Suggester: Suggest internal links from your page list into a draft using keyword overlap scoring" },
  "seo-web-tools/keyword-combiner": { slug: "keyword-combiner-guide", title: "Keyword Combiner: Combine and permute keyword lists into broad/phrase/exact match" },
  "seo-web-tools/keyword-density-checker": { slug: "keyword-density-checker-guide", title: "Keyword Density Checker: Count word frequency and density percentages in pasted text or HTML" },
  "seo-web-tools/keyword-difficulty-estimator": { slug: "keyword-difficulty-estimator-guide", title: "Keyword Difficulty Estimator: Estimate keyword competitiveness from SERP signals like brands, content length, and authority" },
  "seo-web-tools/keyword-rank-tracker": { slug: "keyword-rank-tracker-guide", title: "Keyword Rank Tracker: Log keyword rankings over time in your browser and export CSV reports — no API key required" },
  "seo-web-tools/llms-txt-generator": { slug: "llms-txt-generator-guide", title: "LLMs.txt Generator: Build an llms.txt file so AI crawlers (ChatGPT, Claude, Google) discover your best pages" },
  "seo-web-tools/local-business-schema-generator": { slug: "local-business-schema-generator-guide", title: "Local Business Schema Generator: Create LocalBusiness JSON-LD with NAP, geo coordinates, and business type" },
  "seo-web-tools/meta-description-length-checker": { slug: "meta-description-length-checker-guide", title: "Meta Description Length Checker: Check meta description length with a live Google search preview" },
  "seo-web-tools/meta-tag-generator": { slug: "meta-tag-generator-guide", title: "Meta Tag Generator: Generate title, description, and meta tags HTML from form inputs" },
  "seo-web-tools/meta-tags-analyzer": { slug: "meta-tags-analyzer-guide", title: "Meta Tags Analyzer: Parse pasted HTML to extract and audit meta tags for SEO issues" },
  "seo-web-tools/meta-title-length-checker": { slug: "meta-title-length-checker-guide", title: "Meta Title Length Checker: Check if your page title is the right length for Google search results" },
  "seo-web-tools/nap-consistency-checker": { slug: "nap-consistency-checker-guide", title: "NAP Consistency Checker: Compare Name, Address, Phone across local citations to catch local SEO inconsistencies" },
  "seo-web-tools/open-graph-generator": { slug: "open-graph-generator-guide", title: "Open Graph Generator: Produce Open Graph (og:) meta tags for social link previews" },
  "seo-web-tools/orphan-page-finder": { slug: "orphan-page-finder-guide", title: "Orphan Page Finder: Find sitemap URLs with no internal links and linked URLs missing from the sitemap" },
  "seo-web-tools/readability-checker": { slug: "readability-checker-guide", title: "Readability Score Checker: Compute Flesch reading ease and grade-level scores for text" },
  "seo-web-tools/redirect-checker": { slug: "redirect-checker-guide", title: "Redirect Checker: Follow a live URL and list every redirect hop, status code, and final destination" },
  "seo-web-tools/related-keywords-generator": { slug: "related-keywords-generator-guide", title: "Related Keywords Generator: Expand seed keywords into questions, commercial modifiers, long-tail phrases, and combinations for research" },
  "seo-web-tools/robots-meta-tag-generator": { slug: "robots-meta-tag-generator-guide", title: "Robots Meta Tag Generator: Generate index/noindex/follow robots meta directives" },
  "seo-web-tools/robots-txt-generator": { slug: "robots-txt-generator-guide", title: "Robots.txt Generator: Build a valid robots.txt file from allow/disallow and sitemap inputs" },
  "seo-web-tools/robots-txt-validator": { slug: "robots-txt-validator-guide", title: "Robots.txt Validator: Validate robots.txt syntax and test URL allow/block rules" },
  "seo-web-tools/schema-markup-generator": { slug: "schema-markup-generator-guide", title: "Schema Markup Generator: Generate JSON-LD structured data for articles, products, FAQs, and more" },
  "seo-web-tools/schema-markup-validator": { slug: "schema-markup-validator-guide", title: "Schema Markup Validator: Validate JSON-LD structure for FAQ, HowTo, Product, LocalBusiness, and common schema errors" },
  "seo-web-tools/search-intent-classifier": { slug: "search-intent-classifier-guide", title: "Search Intent Classifier: Classify keywords as informational, commercial, transactional, or navigational with page-type suggestions" },
  "seo-web-tools/security-headers-generator": { slug: "security-headers-generator-guide", title: "Security Headers Generator: Generate HSTS, CSP, X-Frame-Options and other OWASP headers for Nginx, Apache, or Cloudflare" },
  "seo-web-tools/seo-audit-checklist": { slug: "seo-audit-checklist-guide", title: "SEO Audit Checklist: Interactive technical, on-page, E-E-A-T, and link audit checklist with progress saved in your browser" },
  "seo-web-tools/seo-content-score": { slug: "seo-content-score-guide", title: "SEO Content Score: Score on-page SEO for a draft — keyword placement, density, title/meta length, and scannability" },
  "seo-web-tools/serp-snippet-preview": { slug: "serp-snippet-preview-guide", title: "SERP Snippet Preview: Preview how a page appears in Google results with pixel-width checks" },
  "seo-web-tools/twitter-card-generator": { slug: "twitter-card-generator-guide", title: "Twitter Card Generator: Build Twitter/X card meta tags and preview the card" },
  "seo-web-tools/url-index-status-checker": { slug: "url-index-status-checker-guide", title: "URL Index Status Checker: Soft-check whether a URL appears indexed and open Google/Bing site: verification links" },
  "seo-web-tools/url-indexing-toolkit": { slug: "url-indexing-toolkit-guide", title: "URL Indexing Toolkit: Track URLs, audit index readiness, submit IndexNow to Bing/Yandex, and verify site: index status — an honest indexing " },
  "seo-web-tools/url-page-seo-analyzer": { slug: "url-page-seo-analyzer-guide", title: "URL Page SEO Analyzer: Paste a page URL to fetch live HTML and audit title, meta, headings, schema, images, and links" },
  "seo-web-tools/url-slug-generator": { slug: "url-slug-generator-guide", title: "URL Slug Generator: Convert titles into clean SEO-friendly slugs with stop-word removal" },
  "seo-web-tools/utm-builder": { slug: "utm-builder-guide", title: "How to Build UTM Links That Actually Track in GA4" },
  "seo-web-tools/xml-sitemap-generator": { slug: "xml-sitemap-generator-guide", title: "XML Sitemap Generator: Create an XML sitemap from a list of URLs with priority and frequency" },
  "seo-web-tools/xml-sitemap-validator": { slug: "xml-sitemap-validator-guide", title: "XML Sitemap Validator: Validate sitemap XML for parse errors, bad URLs, duplicates, lastmod dates, and the 50k limit" },
  "social-media-tools/aesthetic-username-generator": { slug: "aesthetic-username-generator-guide", title: "Aesthetic Username Generator: Generate decorated usernames with symbols and aesthetic fonts" },
  "social-media-tools/bold-text-generator": { slug: "bold-text-generator-guide", title: "Bold Text Generator: Convert text into bold Unicode for platforms without formatting" },
  "social-media-tools/cursive-text-generator": { slug: "cursive-text-generator-guide", title: "Cursive Text Generator: Generate cursive and italic Unicode text styles" },
  "social-media-tools/discord-font-generator": { slug: "discord-font-generator-guide", title: "Discord Font Generator: Produce fancy and formatted text usable in Discord chats" },
  "social-media-tools/emoji-picker": { slug: "emoji-picker-guide", title: "Emoji Picker: Searchable emoji keyboard for copying emojis into posts" },
  "social-media-tools/fake-facebook-post-generator": { slug: "fake-facebook-post-generator-guide", title: "Fake Facebook Post Generator: Create Facebook post mockups with reactions and comments" },
  "social-media-tools/fake-instagram-dm-generator": { slug: "fake-instagram-dm-generator-guide", title: "Fake Instagram DM Generator: Mock up Instagram DM chat and profile screenshots" },
  "social-media-tools/fake-instagram-post-generator": { slug: "fake-instagram-post-generator-guide", title: "Fake Instagram Post Generator: Generate realistic Instagram post mockups with custom likes and avatar" },
  "social-media-tools/fake-tweet-generator": { slug: "fake-tweet-generator-guide", title: "Fake Tweet Generator: Create realistic X/Twitter post mockups downloadable as images" },
  "social-media-tools/glitch-text-generator": { slug: "glitch-text-generator-guide", title: "Glitch Text Generator: Generate zalgo/glitch styled text for posts and usernames" },
  "social-media-tools/hashtag-counter": { slug: "hashtag-counter-guide", title: "Hashtag Counter: Count hashtags in text and flag platform over-limits" },
  "social-media-tools/instagram-bio-generator": { slug: "instagram-bio-generator-guide", title: "Instagram Bio Generator: Build stylish IG bios with line breaks, fonts, and symbols" },
  "social-media-tools/instagram-caption-generator": { slug: "instagram-caption-generator-guide", title: "Instagram Caption Generator: Generate caption ideas from a topic plus hashtags and emojis" },
  "social-media-tools/instagram-font-generator": { slug: "instagram-font-generator-guide", title: "Instagram Font Generator: Convert text into copy-paste Unicode fancy fonts for bios and captions" },
  "social-media-tools/instagram-hashtag-generator": { slug: "instagram-hashtag-generator-guide", title: "Instagram Hashtag Generator: Suggest and group relevant hashtags from keywords or topics" },
  "social-media-tools/instagram-line-break-generator": { slug: "instagram-line-break-generator-guide", title: "Instagram Line Break Generator: Add invisible spacing so captions keep line breaks on Instagram" },
  "social-media-tools/linkedin-text-formatter": { slug: "linkedin-text-formatter-guide", title: "LinkedIn Text Formatter: Add bold/italic Unicode formatting to LinkedIn posts" },
  "social-media-tools/small-text-generator": { slug: "small-text-generator-guide", title: "Small Text Generator: Convert text to superscript and small-caps Unicode characters" },
  "social-media-tools/social-media-image-sizes": { slug: "social-media-image-sizes-guide", title: "Social Media Image Sizes: Reference of current image/video dimensions per platform" },
  "social-media-tools/social-preview-tester": { slug: "social-preview-tester-guide", title: "Social Preview Tester: Preview how a link will look when shared across platforms" },
  "social-media-tools/tiktok-hashtag-generator": { slug: "tiktok-hashtag-generator-guide", title: "TikTok Hashtag Generator: Generate trending-style hashtags and captions for TikTok" },
  "social-media-tools/tweet-to-image": { slug: "tweet-to-image-guide", title: "Tweet to Image: Turn real or custom tweet text into a shareable styled image" },
  "social-media-tools/twitch-text-generator": { slug: "twitch-text-generator-guide", title: "Twitch Text Generator: Create stylized text and name ideas for Twitch profiles" },
  "social-media-tools/twitter-bio-generator": { slug: "twitter-bio-generator-guide", title: "Twitter Bio Generator: Build X/Twitter bios with fonts, line breaks, and emojis" },
  "social-media-tools/twitter-character-counter": { slug: "twitter-character-counter-guide", title: "Twitter Character Counter: Count characters against the 280-limit with weighted counting" },
  "social-media-tools/whatsapp-link-generator": { slug: "whatsapp-link-generator-guide", title: "WhatsApp Link Generator: Create wa.me click-to-chat links with prefilled messages" },
  "social-media-tools/youtube-tag-extractor": { slug: "youtube-tag-extractor-guide", title: "YouTube Tag Extractor: Extract video tags from a YouTube URL or page source" },
  "social-media-tools/youtube-thumbnail-downloader": { slug: "youtube-thumbnail-downloader-guide", title: "YouTube Thumbnail Downloader: Grab all thumbnail sizes from a YouTube video URL" },
  "text-tools/add-line-numbers": { slug: "add-line-numbers-guide", title: "Add Line Numbers: Prepend sequential line numbers to each line of text" },
  "text-tools/binary-translator": { slug: "binary-translator-guide", title: "Binary Translator: Convert text to binary and binary back to readable text" },
  "text-tools/bionic-reading-converter": { slug: "bionic-reading-converter-guide", title: "Bionic Reading Converter: Bold the leading part of each word to aid faster reading" },
  "text-tools/capitalize-each-word": { slug: "capitalize-each-word-guide", title: "Capitalize Each Word: Capitalize the first letter of every word in the input" },
  "text-tools/case-converter": { slug: "case-converter-guide", title: "Case Converter: Convert text to UPPERCASE, lowercase, Title Case, Sentence case and more" },
  "text-tools/character-counter": { slug: "character-counter-guide", title: "Character Counter: Count characters with and without spaces in real time for tweets and bios" },
  "text-tools/fancy-text-generator": { slug: "fancy-text-generator-guide", title: "Fancy Text Generator: Turn text into stylish Unicode fonts for social media bios" },
  "text-tools/find-and-replace-text": { slug: "find-and-replace-text-guide", title: "Find and Replace Text: Find and replace words or patterns in bulk text, with regex support" },
  "text-tools/language-translator": { slug: "language-translator-guide", title: "Language Translator: Translate text or CSV/Excel into one or many languages — each target gets its own column named after that language" },
  "text-tools/lorem-ipsum-generator": { slug: "lorem-ipsum-generator-guide", title: "Lorem Ipsum Generator: Generate placeholder dummy text by paragraphs, sentences or words" },
  "text-tools/morse-code-translator": { slug: "morse-code-translator-guide", title: "Morse Code Translator: Encode and decode between text and Morse code, with optional audio" },
  "text-tools/nato-phonetic-alphabet-converter": { slug: "nato-phonetic-alphabet-converter-guide", title: "NATO Phonetic Alphabet: Spell text using the NATO phonetic alphabet" },
  "text-tools/reading-time-calculator": { slug: "reading-time-calculator-guide", title: "Reading Time Calculator: Estimate how long it takes to read any text based on words per minute" },
  "text-tools/remove-duplicate-lines": { slug: "remove-duplicate-lines-guide", title: "Remove Duplicate Lines: Delete duplicate lines from a list while preserving order" },
  "text-tools/remove-extra-spaces": { slug: "remove-extra-spaces-guide", title: "Remove Extra Spaces: Remove duplicate, leading and trailing whitespace from text" },
  "text-tools/remove-line-breaks": { slug: "remove-line-breaks-guide", title: "Remove Line Breaks: Strip or merge line breaks and extra newlines from pasted text" },
  "text-tools/remove-punctuation": { slug: "remove-punctuation-guide", title: "Remove Punctuation: Strip punctuation marks from text for clean processing" },
  "text-tools/reverse-text": { slug: "reverse-text-guide", title: "Reverse Text: Reverse characters, words or lines of any input text" },
  "text-tools/sentence-counter": { slug: "sentence-counter-guide", title: "Sentence Counter: Count sentences and average sentence length in text" },
  "text-tools/sort-text-lines": { slug: "sort-text-lines-guide", title: "Sort Text Lines: Sort lines alphabetically, numerically or reverse their order" },
  "text-tools/speech-to-text": { slug: "speech-to-text-guide", title: "Speech to Text: Dictate speech into editable text in your browser with live transcript and multi-language support" },
  "text-tools/strikethrough-text-generator": { slug: "strikethrough-text-generator-guide", title: "Strikethrough Text Generator: Add strikethrough or underline Unicode styling to text" },
  "text-tools/text-diff-checker": { slug: "text-diff-checker-guide", title: "Text Diff Checker: Highlight additions and deletions between two blocks of text" },
  "text-tools/text-repeater": { slug: "text-repeater-guide", title: "Text Repeater: Repeat a string or line a chosen number of times" },
  "text-tools/text-to-ascii-art": { slug: "text-to-ascii-art-guide", title: "Text to ASCII Art: Convert words into large ASCII banner art" },
  "text-tools/text-to-handwriting": { slug: "text-to-handwriting-guide", title: "Text to Handwriting: Render typed text as realistic handwriting on paper" },
  "text-tools/text-to-slug": { slug: "text-to-slug-guide", title: "Text to Slug: Convert a title or phrase into a clean URL-friendly slug" },
  "text-tools/text-to-speech": { slug: "elevenlabs-vs-browser-text-to-speech", title: "ElevenLabs vs Browser Text to Speech — Paid AI Voice or Free Device Voices?" },
  "text-tools/title-case-converter": { slug: "title-case-converter-guide", title: "Title Case Converter: Apply proper title capitalization rules to headlines" },
  "text-tools/upside-down-text-generator": { slug: "upside-down-text-generator-guide", title: "Upside Down Text: Flip text into upside-down Unicode characters" },
  "text-tools/whitespace-remover": { slug: "whitespace-remover-guide", title: "Whitespace Remover: Strip all whitespace or collapse multiple spaces into one" },
  "text-tools/word-counter": { slug: "grammarly-vs-chatgpt-for-writing", title: "Grammarly vs ChatGPT for Writing — Editor or Drafter?" },
  "text-tools/word-frequency-counter": { slug: "word-frequency-counter-guide", title: "Word Frequency Counter: Count how often each word appears and rank them by frequency" },
  "unit-converters/angle-converter": { slug: "angle-converter-guide", title: "Angle Converter: Convert degrees, radians, gradians, and arcminutes" },
  "unit-converters/area-converter": { slug: "area-converter-guide", title: "Area Converter: Convert square meters, acres, hectares, square feet, and more" },
  "unit-converters/binary-to-decimal-converter": { slug: "binary-to-decimal-converter-guide", title: "Binary to Decimal Converter: Convert numbers between binary, decimal, hex, and octal" },
  "unit-converters/bra-size-converter": { slug: "bra-size-converter-guide", title: "Bra Size Converter: Convert bra sizes between US, UK, EU, and FR systems" },
  "unit-converters/clothing-size-converter": { slug: "clothing-size-converter-guide", title: "Clothing Size Converter: Convert clothing sizes across US, UK, EU, and international charts" },
  "unit-converters/cooking-measurement-converter": { slug: "cooking-measurement-converter-guide", title: "Cooking Measurement Converter: Convert cups, tablespoons, teaspoons, grams, and ounces for recipes" },
  "unit-converters/currency-converter": { slug: "currency-converter-guide", title: "Currency Converter: Convert between USD, EUR, PKR, INR, AED and more with live mid-market rates" },
  "unit-converters/data-storage-converter": { slug: "data-storage-converter-guide", title: "Data Storage Converter: Convert bytes, kilobytes, megabytes, gigabytes, and terabytes" },
  "unit-converters/data-transfer-rate-converter": { slug: "data-transfer-rate-converter-guide", title: "Data Transfer Rate Converter: Convert bps, Kbps, Mbps, Gbps, and MB/s" },
  "unit-converters/density-converter": { slug: "density-converter-guide", title: "Density Converter: Convert kg/m3, g/cm3, lb/ft3, and other density units" },
  "unit-converters/energy-converter": { slug: "energy-converter-guide", title: "Energy Converter: Convert joules, calories, kilowatt-hours, and BTU" },
  "unit-converters/force-converter": { slug: "force-converter-guide", title: "Force Converter: Convert newtons, pounds-force, kilogram-force, and dynes" },
  "unit-converters/frequency-converter": { slug: "frequency-converter-guide", title: "Frequency Converter: Convert hertz, kilohertz, megahertz, and gigahertz" },
  "unit-converters/fuel-consumption-converter": { slug: "fuel-consumption-converter-guide", title: "Fuel Consumption Converter: Convert MPG, km/L, and L/100km fuel economy units" },
  "unit-converters/inches-to-cm-converter": { slug: "inches-to-cm-converter-guide", title: "Inches to CM Converter: Dedicated converter between inches and centimeters" },
  "unit-converters/kg-to-lbs-converter": { slug: "kg-to-lbs-converter-guide", title: "KG to Lbs Converter: Dedicated converter between kilograms and pounds" },
  "unit-converters/length-converter": { slug: "length-converter-guide", title: "Length Converter: Convert between meters, feet, miles, kilometers, inches, and more" },
  "unit-converters/liters-to-gallons-converter": { slug: "liters-to-gallons-converter-guide", title: "Liters to Gallons Converter: Dedicated converter between liters and US/UK gallons" },
  "unit-converters/number-to-words-converter": { slug: "number-to-words-converter-guide", title: "Number to Words Converter: Spell out numbers in words for checks and documents" },
  "unit-converters/power-converter": { slug: "power-converter-guide", title: "Power Converter: Convert watts, kilowatts, horsepower, and BTU/hour" },
  "unit-converters/pressure-converter": { slug: "pressure-converter-guide", title: "Pressure Converter: Convert pascals, bar, psi, atm, and mmHg" },
  "unit-converters/ring-size-converter": { slug: "ring-size-converter-guide", title: "Ring Size Converter: Convert ring sizes across US, UK, EU, and diameter charts" },
  "unit-converters/roman-numeral-converter": { slug: "roman-numeral-converter-guide", title: "Roman Numeral Converter: Convert numbers to Roman numerals and back" },
  "unit-converters/shoe-size-converter": { slug: "shoe-size-converter-guide", title: "Shoe Size Converter: Convert shoe sizes between US, UK, EU, and centimeters" },
  "unit-converters/speed-converter": { slug: "speed-converter-guide", title: "Speed Converter: Convert mph, km/h, m/s, knots, and other speed units" },
  "unit-converters/temperature-converter": { slug: "temperature-converter-guide", title: "Temperature Converter: Convert between Celsius, Fahrenheit, and Kelvin" },
  "unit-converters/time-converter": { slug: "time-converter-guide", title: "Time Converter: Convert seconds, minutes, hours, days, weeks, and years" },
  "unit-converters/time-zone-converter": { slug: "time-zone-converter-guide", title: "Time Zone Converter: Convert a time between different world time zones" },
  "unit-converters/volume-converter": { slug: "volume-converter-guide", title: "Volume Converter: Convert liters, gallons, cups, milliliters, and other volume units" },
  "unit-converters/weight-converter": { slug: "weight-converter-guide", title: "Weight Converter: Convert mass units like kilograms, pounds, ounces, and grams" },
};
