export const FORM_COUNTRIES = [
  { code: "all", label: "All countries" },
  { code: "global", label: "Universal / International" },
  { code: "pk", label: "Pakistan" },
  { code: "in", label: "India" },
  { code: "bd", label: "Bangladesh" },
  { code: "us", label: "United States" },
  { code: "gb", label: "United Kingdom" },
  { code: "ca", label: "Canada" },
  { code: "au", label: "Australia" },
  { code: "ae", label: "United Arab Emirates" },
  { code: "sa", label: "Saudi Arabia" },
  { code: "de", label: "Germany" },
  { code: "fr", label: "France" },
  { code: "es", label: "Spain" },
  { code: "it", label: "Italy" },
  { code: "nl", label: "Netherlands" },
  { code: "tr", label: "Turkey" },
  { code: "cn", label: "China" },
  { code: "jp", label: "Japan" },
  { code: "kr", label: "South Korea" },
  { code: "br", label: "Brazil" },
  { code: "mx", label: "Mexico" },
  { code: "ng", label: "Nigeria" },
  { code: "za", label: "South Africa" },
  { code: "eg", label: "Egypt" },
  { code: "id", label: "Indonesia" },
  { code: "my", label: "Malaysia" },
  { code: "ph", label: "Philippines" },
  { code: "ru", label: "Russia" },
  { code: "pl", label: "Poland" },
] as const;
